//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/Users/PC/Desktop/ProjectsAn2/LFC/ANTLRTest/ANTLRTest/Compiler.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


namespace ANTLRTest;

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class CompilerParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		BUILTIN_FUNC=1, SINGLE_LINE_COMMENT=2, MULTI_LINE_COMMENT=3, COMMENT=4, 
		IF_TOKEN=5, ELSE_TOKEN=6, FOR_TOKEN=7, WHILE_TOKEN=8, RETURN_TOKEN=9, 
		FLOAT_DOUBLE_TOKEN=10, INT_TOKEN=11, STRING_TOKEN=12, WS=13, INT_TYPE=14, 
		DOUBLE_TYPE=15, FLOAT_TYPE=16, STRING_TYPE=17, PLUS=18, MINUS=19, MUL=20, 
		DIV=21, MOD=22, ASSIGN=23, INCR=24, DECR=25, PLUS_EQ=26, MINUS_EQ=27, 
		MUL_EQ=28, DIV_EQ=29, MOD_EQ=30, LPAREN=31, RPAREN=32, SEMICOL=33, COMMA=34, 
		DOT=35, LBRACE=36, RBRACE=37, LBRACK=38, RBRACK=39, LT=40, LEQ=41, GT=42, 
		GEQ=43, EQ=44, NEQ=45, DQUOTE=46, BINARY_LOGICAL_OP=47, UNARY_LOGICAL_OP=48, 
		TRUE=49, FALSE=50, NULL=51, MAIN=52, SQRT=53, LOG=54, SIN=55, COS=56, 
		ID=57;
	public const int
		RULE_program = 0, RULE_varType = 1, RULE_numericType = 2, RULE_stringType = 3, 
		RULE_statement = 4, RULE_ifStatement = 5, RULE_forStatement = 6, RULE_whileStatement = 7, 
		RULE_returnStatement = 8, RULE_expression = 9, RULE_number = 10, RULE_string = 11, 
		RULE_singleLogicalExpr = 12, RULE_logicalExpr = 13, RULE_varDeclaration = 14, 
		RULE_varAssignment = 15, RULE_varValue = 16, RULE_arithmExpr = 17, RULE_atom = 18, 
		RULE_arithmOperation = 19, RULE_comparators = 20, RULE_logicalOp = 21, 
		RULE_functionCall = 22, RULE_mainFunction = 23;
	public static readonly string[] ruleNames = {
		"program", "varType", "numericType", "stringType", "statement", "ifStatement", 
		"forStatement", "whileStatement", "returnStatement", "expression", "number", 
		"string", "singleLogicalExpr", "logicalExpr", "varDeclaration", "varAssignment", 
		"varValue", "arithmExpr", "atom", "arithmOperation", "comparators", "logicalOp", 
		"functionCall", "mainFunction"
	};

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, "'if'", "'else'", "'for'", "'while'", "'return'", 
		null, null, null, null, "'int'", "'double'", "'float'", "'string'", "'+'", 
		"'-'", "'*'", "'/'", "'%'", "'='", "'++'", "'--'", "'+='", "'-='", "'*='", 
		"'/='", "'%='", "'('", "')'", "';'", "','", "'.'", "'{'", "'}'", "'['", 
		"']'", "'<'", "'<='", "'>'", "'>='", "'=='", "'!='", "'\"'", null, "'!'", 
		"'true'", "'false'", "'null'", "'main'", "'sqrt'", "'log'", "'sin'", "'cos'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "BUILTIN_FUNC", "SINGLE_LINE_COMMENT", "MULTI_LINE_COMMENT", "COMMENT", 
		"IF_TOKEN", "ELSE_TOKEN", "FOR_TOKEN", "WHILE_TOKEN", "RETURN_TOKEN", 
		"FLOAT_DOUBLE_TOKEN", "INT_TOKEN", "STRING_TOKEN", "WS", "INT_TYPE", "DOUBLE_TYPE", 
		"FLOAT_TYPE", "STRING_TYPE", "PLUS", "MINUS", "MUL", "DIV", "MOD", "ASSIGN", 
		"INCR", "DECR", "PLUS_EQ", "MINUS_EQ", "MUL_EQ", "DIV_EQ", "MOD_EQ", "LPAREN", 
		"RPAREN", "SEMICOL", "COMMA", "DOT", "LBRACE", "RBRACE", "LBRACK", "RBRACK", 
		"LT", "LEQ", "GT", "GEQ", "EQ", "NEQ", "DQUOTE", "BINARY_LOGICAL_OP", 
		"UNARY_LOGICAL_OP", "TRUE", "FALSE", "NULL", "MAIN", "SQRT", "LOG", "SIN", 
		"COS", "ID"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Compiler.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static CompilerParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public CompilerParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public CompilerParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public MainFunctionContext mainFunction() {
			return GetRuleContext<MainFunctionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(CompilerParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 51;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,0,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 48;
					statement();
					}
					} 
				}
				State = 53;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,0,Context);
			}
			State = 54;
			mainFunction();
			State = 58;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 144115198813523874L) != 0)) {
				{
				{
				State = 55;
				statement();
				}
				}
				State = 60;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 61;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VarTypeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT_TYPE() { return GetToken(CompilerParser.INT_TYPE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOUBLE_TYPE() { return GetToken(CompilerParser.DOUBLE_TYPE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FLOAT_TYPE() { return GetToken(CompilerParser.FLOAT_TYPE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING_TYPE() { return GetToken(CompilerParser.STRING_TYPE, 0); }
		public VarTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_varType; } }
	}

	[RuleVersion(0)]
	public VarTypeContext varType() {
		VarTypeContext _localctx = new VarTypeContext(Context, State);
		EnterRule(_localctx, 2, RULE_varType);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 63;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 245760L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumericTypeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT_TYPE() { return GetToken(CompilerParser.INT_TYPE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOUBLE_TYPE() { return GetToken(CompilerParser.DOUBLE_TYPE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FLOAT_TYPE() { return GetToken(CompilerParser.FLOAT_TYPE, 0); }
		public NumericTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_numericType; } }
	}

	[RuleVersion(0)]
	public NumericTypeContext numericType() {
		NumericTypeContext _localctx = new NumericTypeContext(Context, State);
		EnterRule(_localctx, 4, RULE_numericType);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 65;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 114688L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StringTypeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING_TYPE() { return GetToken(CompilerParser.STRING_TYPE, 0); }
		public StringTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stringType; } }
	}

	[RuleVersion(0)]
	public StringTypeContext stringType() {
		StringTypeContext _localctx = new StringTypeContext(Context, State);
		EnterRule(_localctx, 6, RULE_stringType);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 67;
			Match(STRING_TYPE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOL() { return GetToken(CompilerParser.SEMICOL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public VarDeclarationContext varDeclaration() {
			return GetRuleContext<VarDeclarationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public VarAssignmentContext varAssignment() {
			return GetRuleContext<VarAssignmentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext arithmExpr() {
			return GetRuleContext<ArithmExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IfStatementContext ifStatement() {
			return GetRuleContext<IfStatementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ForStatementContext forStatement() {
			return GetRuleContext<ForStatementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public WhileStatementContext whileStatement() {
			return GetRuleContext<WhileStatementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ReturnStatementContext returnStatement() {
			return GetRuleContext<ReturnStatementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionCallContext functionCall() {
			return GetRuleContext<FunctionCallContext>(0);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 8, RULE_statement);
		try {
			State = 86;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 69;
				Match(SEMICOL);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 70;
				varDeclaration();
				State = 71;
				Match(SEMICOL);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 73;
				varAssignment();
				State = 74;
				Match(SEMICOL);
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 76;
				arithmExpr(0);
				State = 77;
				Match(SEMICOL);
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 79;
				ifStatement();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 80;
				forStatement();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 81;
				whileStatement();
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 82;
				returnStatement();
				}
				break;
			case 9:
				EnterOuterAlt(_localctx, 9);
				{
				State = 83;
				functionCall();
				State = 84;
				Match(SEMICOL);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IfStatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IF_TOKEN() { return GetToken(CompilerParser.IF_TOKEN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(CompilerParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public LogicalExprContext logicalExpr() {
			return GetRuleContext<LogicalExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(CompilerParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] LBRACE() { return GetTokens(CompilerParser.LBRACE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE(int i) {
			return GetToken(CompilerParser.LBRACE, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] RBRACE() { return GetTokens(CompilerParser.RBRACE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE(int i) {
			return GetToken(CompilerParser.RBRACE, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ELSE_TOKEN() { return GetToken(CompilerParser.ELSE_TOKEN, 0); }
		public IfStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ifStatement; } }
	}

	[RuleVersion(0)]
	public IfStatementContext ifStatement() {
		IfStatementContext _localctx = new IfStatementContext(Context, State);
		EnterRule(_localctx, 10, RULE_ifStatement);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 88;
			Match(IF_TOKEN);
			State = 89;
			Match(LPAREN);
			State = 90;
			logicalExpr();
			State = 91;
			Match(RPAREN);
			State = 92;
			Match(LBRACE);
			State = 96;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 144115198813523874L) != 0)) {
				{
				{
				State = 93;
				statement();
				}
				}
				State = 98;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 99;
			Match(RBRACE);
			State = 109;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ELSE_TOKEN) {
				{
				State = 100;
				Match(ELSE_TOKEN);
				State = 101;
				Match(LBRACE);
				State = 105;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 144115198813523874L) != 0)) {
					{
					{
					State = 102;
					statement();
					}
					}
					State = 107;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 108;
				Match(RBRACE);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ForStatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FOR_TOKEN() { return GetToken(CompilerParser.FOR_TOKEN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(CompilerParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SEMICOL() { return GetTokens(CompilerParser.SEMICOL); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOL(int i) {
			return GetToken(CompilerParser.SEMICOL, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(CompilerParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(CompilerParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(CompilerParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public VarDeclarationContext varDeclaration() {
			return GetRuleContext<VarDeclarationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public LogicalExprContext logicalExpr() {
			return GetRuleContext<LogicalExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public VarAssignmentContext varAssignment() {
			return GetRuleContext<VarAssignmentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public ForStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_forStatement; } }
	}

	[RuleVersion(0)]
	public ForStatementContext forStatement() {
		ForStatementContext _localctx = new ForStatementContext(Context, State);
		EnterRule(_localctx, 12, RULE_forStatement);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 111;
			Match(FOR_TOKEN);
			State = 112;
			Match(LPAREN);
			State = 114;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 245760L) != 0)) {
				{
				State = 113;
				varDeclaration();
				}
			}

			State = 116;
			Match(SEMICOL);
			State = 118;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 148337314874002434L) != 0)) {
				{
				State = 117;
				logicalExpr();
				}
			}

			State = 120;
			Match(SEMICOL);
			State = 122;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ID) {
				{
				State = 121;
				varAssignment();
				}
			}

			State = 124;
			Match(RPAREN);
			State = 125;
			Match(LBRACE);
			State = 129;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 144115198813523874L) != 0)) {
				{
				{
				State = 126;
				statement();
				}
				}
				State = 131;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 132;
			Match(RBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class WhileStatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WHILE_TOKEN() { return GetToken(CompilerParser.WHILE_TOKEN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(CompilerParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(CompilerParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(CompilerParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(CompilerParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public LogicalExprContext logicalExpr() {
			return GetRuleContext<LogicalExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public WhileStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_whileStatement; } }
	}

	[RuleVersion(0)]
	public WhileStatementContext whileStatement() {
		WhileStatementContext _localctx = new WhileStatementContext(Context, State);
		EnterRule(_localctx, 14, RULE_whileStatement);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 134;
			Match(WHILE_TOKEN);
			State = 135;
			Match(LPAREN);
			State = 137;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 148337314874002434L) != 0)) {
				{
				State = 136;
				logicalExpr();
				}
			}

			State = 139;
			Match(RPAREN);
			State = 140;
			Match(LBRACE);
			State = 144;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 144115198813523874L) != 0)) {
				{
				{
				State = 141;
				statement();
				}
				}
				State = 146;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 147;
			Match(RBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ReturnStatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RETURN_TOKEN() { return GetToken(CompilerParser.RETURN_TOKEN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOL() { return GetToken(CompilerParser.SEMICOL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ReturnStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_returnStatement; } }
	}

	[RuleVersion(0)]
	public ReturnStatementContext returnStatement() {
		ReturnStatementContext _localctx = new ReturnStatementContext(Context, State);
		EnterRule(_localctx, 16, RULE_returnStatement);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 149;
			Match(RETURN_TOKEN);
			State = 151;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 144115190223346690L) != 0)) {
				{
				State = 150;
				expression();
				}
			}

			State = 153;
			Match(SEMICOL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext arithmExpr() {
			return GetRuleContext<ArithmExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StringContext @string() {
			return GetRuleContext<StringContext>(0);
		}
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		ExpressionContext _localctx = new ExpressionContext(Context, State);
		EnterRule(_localctx, 18, RULE_expression);
		try {
			State = 157;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case BUILTIN_FUNC:
			case FLOAT_DOUBLE_TOKEN:
			case INT_TOKEN:
			case LPAREN:
			case ID:
				EnterOuterAlt(_localctx, 1);
				{
				State = 155;
				arithmExpr(0);
				}
				break;
			case STRING_TOKEN:
				EnterOuterAlt(_localctx, 2);
				{
				State = 156;
				@string();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumberContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FLOAT_DOUBLE_TOKEN() { return GetToken(CompilerParser.FLOAT_DOUBLE_TOKEN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT_TOKEN() { return GetToken(CompilerParser.INT_TOKEN, 0); }
		public NumberContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_number; } }
	}

	[RuleVersion(0)]
	public NumberContext number() {
		NumberContext _localctx = new NumberContext(Context, State);
		EnterRule(_localctx, 20, RULE_number);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 159;
			_la = TokenStream.LA(1);
			if ( !(_la==FLOAT_DOUBLE_TOKEN || _la==INT_TOKEN) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StringContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING_TOKEN() { return GetToken(CompilerParser.STRING_TOKEN, 0); }
		public StringContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_string; } }
	}

	[RuleVersion(0)]
	public StringContext @string() {
		StringContext _localctx = new StringContext(Context, State);
		EnterRule(_localctx, 22, RULE_string);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 161;
			Match(STRING_TOKEN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SingleLogicalExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext[] arithmExpr() {
			return GetRuleContexts<ArithmExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext arithmExpr(int i) {
			return GetRuleContext<ArithmExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ComparatorsContext comparators() {
			return GetRuleContext<ComparatorsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(CompilerParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public LogicalExprContext logicalExpr() {
			return GetRuleContext<LogicalExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(CompilerParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode UNARY_LOGICAL_OP() { return GetToken(CompilerParser.UNARY_LOGICAL_OP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public SingleLogicalExprContext singleLogicalExpr() {
			return GetRuleContext<SingleLogicalExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(CompilerParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StringContext @string() {
			return GetRuleContext<StringContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TRUE() { return GetToken(CompilerParser.TRUE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FALSE() { return GetToken(CompilerParser.FALSE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NULL() { return GetToken(CompilerParser.NULL, 0); }
		public SingleLogicalExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_singleLogicalExpr; } }
	}

	[RuleVersion(0)]
	public SingleLogicalExprContext singleLogicalExpr() {
		SingleLogicalExprContext _localctx = new SingleLogicalExprContext(Context, State);
		EnterRule(_localctx, 24, RULE_singleLogicalExpr);
		int _la;
		try {
			State = 182;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,15,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 163;
				arithmExpr(0);
				State = 167;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 69269232549888L) != 0)) {
					{
					State = 164;
					comparators();
					State = 165;
					arithmExpr(0);
					}
				}

				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 169;
				Match(LPAREN);
				State = 170;
				logicalExpr();
				State = 171;
				Match(RPAREN);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 173;
				Match(UNARY_LOGICAL_OP);
				State = 174;
				singleLogicalExpr();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 175;
				Match(ID);
				State = 176;
				comparators();
				State = 177;
				@string();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 179;
				Match(TRUE);
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 180;
				Match(FALSE);
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 181;
				Match(NULL);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LogicalExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SingleLogicalExprContext singleLogicalExpr() {
			return GetRuleContext<SingleLogicalExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] BINARY_LOGICAL_OP() { return GetTokens(CompilerParser.BINARY_LOGICAL_OP); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BINARY_LOGICAL_OP(int i) {
			return GetToken(CompilerParser.BINARY_LOGICAL_OP, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public LogicalExprContext[] logicalExpr() {
			return GetRuleContexts<LogicalExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public LogicalExprContext logicalExpr(int i) {
			return GetRuleContext<LogicalExprContext>(i);
		}
		public LogicalExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_logicalExpr; } }
	}

	[RuleVersion(0)]
	public LogicalExprContext logicalExpr() {
		LogicalExprContext _localctx = new LogicalExprContext(Context, State);
		EnterRule(_localctx, 26, RULE_logicalExpr);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 184;
			singleLogicalExpr();
			State = 189;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,16,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 185;
					Match(BINARY_LOGICAL_OP);
					State = 186;
					logicalExpr();
					}
					} 
				}
				State = 191;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,16,Context);
			}
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VarDeclarationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public VarTypeContext varType() {
			return GetRuleContext<VarTypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ID() { return GetTokens(CompilerParser.ID); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID(int i) {
			return GetToken(CompilerParser.ID, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ASSIGN() { return GetTokens(CompilerParser.ASSIGN); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN(int i) {
			return GetToken(CompilerParser.ASSIGN, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(CompilerParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(CompilerParser.COMMA, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext[] arithmExpr() {
			return GetRuleContexts<ArithmExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext arithmExpr(int i) {
			return GetRuleContext<ArithmExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StringContext[] @string() {
			return GetRuleContexts<StringContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StringContext @string(int i) {
			return GetRuleContext<StringContext>(i);
		}
		public VarDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_varDeclaration; } }
	}

	[RuleVersion(0)]
	public VarDeclarationContext varDeclaration() {
		VarDeclarationContext _localctx = new VarDeclarationContext(Context, State);
		EnterRule(_localctx, 28, RULE_varDeclaration);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 192;
			varType();
			{
			State = 193;
			Match(ID);
			State = 199;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ASSIGN) {
				{
				State = 194;
				Match(ASSIGN);
				State = 197;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case BUILTIN_FUNC:
				case FLOAT_DOUBLE_TOKEN:
				case INT_TOKEN:
				case LPAREN:
				case ID:
					{
					State = 195;
					arithmExpr(0);
					}
					break;
				case STRING_TOKEN:
					{
					State = 196;
					@string();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
			}

			State = 212;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 201;
				Match(COMMA);
				State = 202;
				Match(ID);
				State = 208;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==ASSIGN) {
					{
					State = 203;
					Match(ASSIGN);
					State = 206;
					ErrorHandler.Sync(this);
					switch (TokenStream.LA(1)) {
					case BUILTIN_FUNC:
					case FLOAT_DOUBLE_TOKEN:
					case INT_TOKEN:
					case LPAREN:
					case ID:
						{
						State = 204;
						arithmExpr(0);
						}
						break;
					case STRING_TOKEN:
						{
						State = 205;
						@string();
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					}
				}

				}
				}
				State = 214;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VarAssignmentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(CompilerParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN() { return GetToken(CompilerParser.ASSIGN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public VarValueContext varValue() {
			return GetRuleContext<VarValueContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INCR() { return GetToken(CompilerParser.INCR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DECR() { return GetToken(CompilerParser.DECR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUS_EQ() { return GetToken(CompilerParser.PLUS_EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS_EQ() { return GetToken(CompilerParser.MINUS_EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MUL_EQ() { return GetToken(CompilerParser.MUL_EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIV_EQ() { return GetToken(CompilerParser.DIV_EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MOD_EQ() { return GetToken(CompilerParser.MOD_EQ, 0); }
		public VarAssignmentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_varAssignment; } }
	}

	[RuleVersion(0)]
	public VarAssignmentContext varAssignment() {
		VarAssignmentContext _localctx = new VarAssignmentContext(Context, State);
		EnterRule(_localctx, 30, RULE_varAssignment);
		try {
			State = 237;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,22,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 215;
				Match(ID);
				State = 216;
				Match(ASSIGN);
				State = 217;
				varValue();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 218;
				Match(ID);
				State = 219;
				Match(INCR);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 220;
				Match(ID);
				State = 221;
				Match(DECR);
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 222;
				Match(ID);
				State = 223;
				Match(PLUS_EQ);
				State = 224;
				varValue();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 225;
				Match(ID);
				State = 226;
				Match(MINUS_EQ);
				State = 227;
				varValue();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 228;
				Match(ID);
				State = 229;
				Match(MUL_EQ);
				State = 230;
				varValue();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 231;
				Match(ID);
				State = 232;
				Match(DIV_EQ);
				State = 233;
				varValue();
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 234;
				Match(ID);
				State = 235;
				Match(MOD_EQ);
				State = 236;
				varValue();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VarValueContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext arithmExpr() {
			return GetRuleContext<ArithmExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StringContext @string() {
			return GetRuleContext<StringContext>(0);
		}
		public VarValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_varValue; } }
	}

	[RuleVersion(0)]
	public VarValueContext varValue() {
		VarValueContext _localctx = new VarValueContext(Context, State);
		EnterRule(_localctx, 32, RULE_varValue);
		try {
			State = 241;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case BUILTIN_FUNC:
			case FLOAT_DOUBLE_TOKEN:
			case INT_TOKEN:
			case LPAREN:
			case ID:
				EnterOuterAlt(_localctx, 1);
				{
				State = 239;
				arithmExpr(0);
				}
				break;
			case STRING_TOKEN:
				EnterOuterAlt(_localctx, 2);
				{
				State = 240;
				@string();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArithmExprContext : ParserRuleContext {
		public ArithmExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arithmExpr; } }
	 
		public ArithmExprContext() { }
		public virtual void CopyFrom(ArithmExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class FunctionCallExprContext : ArithmExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionCallContext functionCall() {
			return GetRuleContext<FunctionCallContext>(0);
		}
		public FunctionCallExprContext(ArithmExprContext context) { CopyFrom(context); }
	}
	public partial class MulDivExprContext : ArithmExprContext {
		public IToken op;
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext[] arithmExpr() {
			return GetRuleContexts<ArithmExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext arithmExpr(int i) {
			return GetRuleContext<ArithmExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MUL() { return GetToken(CompilerParser.MUL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIV() { return GetToken(CompilerParser.DIV, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MOD() { return GetToken(CompilerParser.MOD, 0); }
		public MulDivExprContext(ArithmExprContext context) { CopyFrom(context); }
	}
	public partial class AtomExprContext : ArithmExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public AtomContext atom() {
			return GetRuleContext<AtomContext>(0);
		}
		public AtomExprContext(ArithmExprContext context) { CopyFrom(context); }
	}
	public partial class AddSubExprContext : ArithmExprContext {
		public IToken op;
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext[] arithmExpr() {
			return GetRuleContexts<ArithmExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext arithmExpr(int i) {
			return GetRuleContext<ArithmExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUS() { return GetToken(CompilerParser.PLUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS() { return GetToken(CompilerParser.MINUS, 0); }
		public AddSubExprContext(ArithmExprContext context) { CopyFrom(context); }
	}

	[RuleVersion(0)]
	public ArithmExprContext arithmExpr() {
		return arithmExpr(0);
	}

	private ArithmExprContext arithmExpr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ArithmExprContext _localctx = new ArithmExprContext(Context, _parentState);
		ArithmExprContext _prevctx = _localctx;
		int _startState = 34;
		EnterRecursionRule(_localctx, 34, RULE_arithmExpr, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 246;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,24,Context) ) {
			case 1:
				{
				_localctx = new AtomExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 244;
				atom();
				}
				break;
			case 2:
				{
				_localctx = new FunctionCallExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 245;
				functionCall();
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 256;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,26,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 254;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,25,Context) ) {
					case 1:
						{
						_localctx = new MulDivExprContext(new ArithmExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_arithmExpr);
						State = 248;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 249;
						((MulDivExprContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 7340032L) != 0)) ) {
							((MulDivExprContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 250;
						arithmExpr(5);
						}
						break;
					case 2:
						{
						_localctx = new AddSubExprContext(new ArithmExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_arithmExpr);
						State = 251;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 252;
						((AddSubExprContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==PLUS || _la==MINUS) ) {
							((AddSubExprContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 253;
						arithmExpr(4);
						}
						break;
					}
					} 
				}
				State = 258;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,26,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class AtomContext : ParserRuleContext {
		public AtomContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_atom; } }
	 
		public AtomContext() { }
		public virtual void CopyFrom(AtomContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class NumberAtomContext : AtomContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberContext number() {
			return GetRuleContext<NumberContext>(0);
		}
		public NumberAtomContext(AtomContext context) { CopyFrom(context); }
	}
	public partial class ParenExprContext : AtomContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(CompilerParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext arithmExpr() {
			return GetRuleContext<ArithmExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(CompilerParser.RPAREN, 0); }
		public ParenExprContext(AtomContext context) { CopyFrom(context); }
	}
	public partial class IdAtomContext : AtomContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(CompilerParser.ID, 0); }
		public IdAtomContext(AtomContext context) { CopyFrom(context); }
	}

	[RuleVersion(0)]
	public AtomContext atom() {
		AtomContext _localctx = new AtomContext(Context, State);
		EnterRule(_localctx, 36, RULE_atom);
		try {
			State = 265;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case FLOAT_DOUBLE_TOKEN:
			case INT_TOKEN:
				_localctx = new NumberAtomContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 259;
				number();
				}
				break;
			case ID:
				_localctx = new IdAtomContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 260;
				Match(ID);
				}
				break;
			case LPAREN:
				_localctx = new ParenExprContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 261;
				Match(LPAREN);
				State = 262;
				arithmExpr(0);
				State = 263;
				Match(RPAREN);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArithmOperationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUS() { return GetToken(CompilerParser.PLUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS() { return GetToken(CompilerParser.MINUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MUL() { return GetToken(CompilerParser.MUL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIV() { return GetToken(CompilerParser.DIV, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MOD() { return GetToken(CompilerParser.MOD, 0); }
		public ArithmOperationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arithmOperation; } }
	}

	[RuleVersion(0)]
	public ArithmOperationContext arithmOperation() {
		ArithmOperationContext _localctx = new ArithmOperationContext(Context, State);
		EnterRule(_localctx, 38, RULE_arithmOperation);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 267;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 8126464L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ComparatorsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LT() { return GetToken(CompilerParser.LT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LEQ() { return GetToken(CompilerParser.LEQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GT() { return GetToken(CompilerParser.GT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GEQ() { return GetToken(CompilerParser.GEQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQ() { return GetToken(CompilerParser.EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEQ() { return GetToken(CompilerParser.NEQ, 0); }
		public ComparatorsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_comparators; } }
	}

	[RuleVersion(0)]
	public ComparatorsContext comparators() {
		ComparatorsContext _localctx = new ComparatorsContext(Context, State);
		EnterRule(_localctx, 40, RULE_comparators);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 269;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 69269232549888L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LogicalOpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BINARY_LOGICAL_OP() { return GetToken(CompilerParser.BINARY_LOGICAL_OP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode UNARY_LOGICAL_OP() { return GetToken(CompilerParser.UNARY_LOGICAL_OP, 0); }
		public LogicalOpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_logicalOp; } }
	}

	[RuleVersion(0)]
	public LogicalOpContext logicalOp() {
		LogicalOpContext _localctx = new LogicalOpContext(Context, State);
		EnterRule(_localctx, 42, RULE_logicalOp);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 271;
			_la = TokenStream.LA(1);
			if ( !(_la==BINARY_LOGICAL_OP || _la==UNARY_LOGICAL_OP) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionCallContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(CompilerParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(CompilerParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(CompilerParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BUILTIN_FUNC() { return GetToken(CompilerParser.BUILTIN_FUNC, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(CompilerParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(CompilerParser.COMMA, i);
		}
		public FunctionCallContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionCall; } }
	}

	[RuleVersion(0)]
	public FunctionCallContext functionCall() {
		FunctionCallContext _localctx = new FunctionCallContext(Context, State);
		EnterRule(_localctx, 44, RULE_functionCall);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 273;
			_la = TokenStream.LA(1);
			if ( !(_la==BUILTIN_FUNC || _la==ID) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 274;
			Match(LPAREN);
			State = 283;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 144115190223346690L) != 0)) {
				{
				State = 275;
				expression();
				State = 280;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==COMMA) {
					{
					{
					State = 276;
					Match(COMMA);
					State = 277;
					expression();
					}
					}
					State = 282;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 285;
			Match(RPAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MainFunctionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT_TYPE() { return GetToken(CompilerParser.INT_TYPE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MAIN() { return GetToken(CompilerParser.MAIN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(CompilerParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(CompilerParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(CompilerParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(CompilerParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public MainFunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_mainFunction; } }
	}

	[RuleVersion(0)]
	public MainFunctionContext mainFunction() {
		MainFunctionContext _localctx = new MainFunctionContext(Context, State);
		EnterRule(_localctx, 46, RULE_mainFunction);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 287;
			Match(INT_TYPE);
			State = 288;
			Match(MAIN);
			State = 289;
			Match(LPAREN);
			State = 290;
			Match(RPAREN);
			State = 291;
			Match(LBRACE);
			State = 295;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 144115198813523874L) != 0)) {
				{
				{
				State = 292;
				statement();
				}
				}
				State = 297;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 298;
			Match(RBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 17: return arithmExpr_sempred((ArithmExprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool arithmExpr_sempred(ArithmExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 4);
		case 1: return Precpred(Context, 3);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,57,301,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,2,23,7,23,1,0,5,0,50,8,0,10,0,12,0,53,9,0,1,0,1,0,5,0,57,8,0,
		10,0,12,0,60,9,0,1,0,1,0,1,1,1,1,1,2,1,2,1,3,1,3,1,4,1,4,1,4,1,4,1,4,1,
		4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,3,4,87,8,4,1,5,1,5,1,5,1,
		5,1,5,1,5,5,5,95,8,5,10,5,12,5,98,9,5,1,5,1,5,1,5,1,5,5,5,104,8,5,10,5,
		12,5,107,9,5,1,5,3,5,110,8,5,1,6,1,6,1,6,3,6,115,8,6,1,6,1,6,3,6,119,8,
		6,1,6,1,6,3,6,123,8,6,1,6,1,6,1,6,5,6,128,8,6,10,6,12,6,131,9,6,1,6,1,
		6,1,7,1,7,1,7,3,7,138,8,7,1,7,1,7,1,7,5,7,143,8,7,10,7,12,7,146,9,7,1,
		7,1,7,1,8,1,8,3,8,152,8,8,1,8,1,8,1,9,1,9,3,9,158,8,9,1,10,1,10,1,11,1,
		11,1,12,1,12,1,12,1,12,3,12,168,8,12,1,12,1,12,1,12,1,12,1,12,1,12,1,12,
		1,12,1,12,1,12,1,12,1,12,1,12,3,12,183,8,12,1,13,1,13,1,13,5,13,188,8,
		13,10,13,12,13,191,9,13,1,14,1,14,1,14,1,14,1,14,3,14,198,8,14,3,14,200,
		8,14,1,14,1,14,1,14,1,14,1,14,3,14,207,8,14,3,14,209,8,14,5,14,211,8,14,
		10,14,12,14,214,9,14,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,
		1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,3,15,238,8,
		15,1,16,1,16,3,16,242,8,16,1,17,1,17,1,17,3,17,247,8,17,1,17,1,17,1,17,
		1,17,1,17,1,17,5,17,255,8,17,10,17,12,17,258,9,17,1,18,1,18,1,18,1,18,
		1,18,1,18,3,18,266,8,18,1,19,1,19,1,20,1,20,1,21,1,21,1,22,1,22,1,22,1,
		22,1,22,5,22,279,8,22,10,22,12,22,282,9,22,3,22,284,8,22,1,22,1,22,1,23,
		1,23,1,23,1,23,1,23,1,23,5,23,294,8,23,10,23,12,23,297,9,23,1,23,1,23,
		1,23,0,1,34,24,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,
		40,42,44,46,0,9,1,0,14,17,1,0,14,16,1,0,10,11,1,0,20,22,1,0,18,19,1,0,
		18,22,1,0,40,45,1,0,47,48,2,0,1,1,57,57,326,0,51,1,0,0,0,2,63,1,0,0,0,
		4,65,1,0,0,0,6,67,1,0,0,0,8,86,1,0,0,0,10,88,1,0,0,0,12,111,1,0,0,0,14,
		134,1,0,0,0,16,149,1,0,0,0,18,157,1,0,0,0,20,159,1,0,0,0,22,161,1,0,0,
		0,24,182,1,0,0,0,26,184,1,0,0,0,28,192,1,0,0,0,30,237,1,0,0,0,32,241,1,
		0,0,0,34,246,1,0,0,0,36,265,1,0,0,0,38,267,1,0,0,0,40,269,1,0,0,0,42,271,
		1,0,0,0,44,273,1,0,0,0,46,287,1,0,0,0,48,50,3,8,4,0,49,48,1,0,0,0,50,53,
		1,0,0,0,51,49,1,0,0,0,51,52,1,0,0,0,52,54,1,0,0,0,53,51,1,0,0,0,54,58,
		3,46,23,0,55,57,3,8,4,0,56,55,1,0,0,0,57,60,1,0,0,0,58,56,1,0,0,0,58,59,
		1,0,0,0,59,61,1,0,0,0,60,58,1,0,0,0,61,62,5,0,0,1,62,1,1,0,0,0,63,64,7,
		0,0,0,64,3,1,0,0,0,65,66,7,1,0,0,66,5,1,0,0,0,67,68,5,17,0,0,68,7,1,0,
		0,0,69,87,5,33,0,0,70,71,3,28,14,0,71,72,5,33,0,0,72,87,1,0,0,0,73,74,
		3,30,15,0,74,75,5,33,0,0,75,87,1,0,0,0,76,77,3,34,17,0,77,78,5,33,0,0,
		78,87,1,0,0,0,79,87,3,10,5,0,80,87,3,12,6,0,81,87,3,14,7,0,82,87,3,16,
		8,0,83,84,3,44,22,0,84,85,5,33,0,0,85,87,1,0,0,0,86,69,1,0,0,0,86,70,1,
		0,0,0,86,73,1,0,0,0,86,76,1,0,0,0,86,79,1,0,0,0,86,80,1,0,0,0,86,81,1,
		0,0,0,86,82,1,0,0,0,86,83,1,0,0,0,87,9,1,0,0,0,88,89,5,5,0,0,89,90,5,31,
		0,0,90,91,3,26,13,0,91,92,5,32,0,0,92,96,5,36,0,0,93,95,3,8,4,0,94,93,
		1,0,0,0,95,98,1,0,0,0,96,94,1,0,0,0,96,97,1,0,0,0,97,99,1,0,0,0,98,96,
		1,0,0,0,99,109,5,37,0,0,100,101,5,6,0,0,101,105,5,36,0,0,102,104,3,8,4,
		0,103,102,1,0,0,0,104,107,1,0,0,0,105,103,1,0,0,0,105,106,1,0,0,0,106,
		108,1,0,0,0,107,105,1,0,0,0,108,110,5,37,0,0,109,100,1,0,0,0,109,110,1,
		0,0,0,110,11,1,0,0,0,111,112,5,7,0,0,112,114,5,31,0,0,113,115,3,28,14,
		0,114,113,1,0,0,0,114,115,1,0,0,0,115,116,1,0,0,0,116,118,5,33,0,0,117,
		119,3,26,13,0,118,117,1,0,0,0,118,119,1,0,0,0,119,120,1,0,0,0,120,122,
		5,33,0,0,121,123,3,30,15,0,122,121,1,0,0,0,122,123,1,0,0,0,123,124,1,0,
		0,0,124,125,5,32,0,0,125,129,5,36,0,0,126,128,3,8,4,0,127,126,1,0,0,0,
		128,131,1,0,0,0,129,127,1,0,0,0,129,130,1,0,0,0,130,132,1,0,0,0,131,129,
		1,0,0,0,132,133,5,37,0,0,133,13,1,0,0,0,134,135,5,8,0,0,135,137,5,31,0,
		0,136,138,3,26,13,0,137,136,1,0,0,0,137,138,1,0,0,0,138,139,1,0,0,0,139,
		140,5,32,0,0,140,144,5,36,0,0,141,143,3,8,4,0,142,141,1,0,0,0,143,146,
		1,0,0,0,144,142,1,0,0,0,144,145,1,0,0,0,145,147,1,0,0,0,146,144,1,0,0,
		0,147,148,5,37,0,0,148,15,1,0,0,0,149,151,5,9,0,0,150,152,3,18,9,0,151,
		150,1,0,0,0,151,152,1,0,0,0,152,153,1,0,0,0,153,154,5,33,0,0,154,17,1,
		0,0,0,155,158,3,34,17,0,156,158,3,22,11,0,157,155,1,0,0,0,157,156,1,0,
		0,0,158,19,1,0,0,0,159,160,7,2,0,0,160,21,1,0,0,0,161,162,5,12,0,0,162,
		23,1,0,0,0,163,167,3,34,17,0,164,165,3,40,20,0,165,166,3,34,17,0,166,168,
		1,0,0,0,167,164,1,0,0,0,167,168,1,0,0,0,168,183,1,0,0,0,169,170,5,31,0,
		0,170,171,3,26,13,0,171,172,5,32,0,0,172,183,1,0,0,0,173,174,5,48,0,0,
		174,183,3,24,12,0,175,176,5,57,0,0,176,177,3,40,20,0,177,178,3,22,11,0,
		178,183,1,0,0,0,179,183,5,49,0,0,180,183,5,50,0,0,181,183,5,51,0,0,182,
		163,1,0,0,0,182,169,1,0,0,0,182,173,1,0,0,0,182,175,1,0,0,0,182,179,1,
		0,0,0,182,180,1,0,0,0,182,181,1,0,0,0,183,25,1,0,0,0,184,189,3,24,12,0,
		185,186,5,47,0,0,186,188,3,26,13,0,187,185,1,0,0,0,188,191,1,0,0,0,189,
		187,1,0,0,0,189,190,1,0,0,0,190,27,1,0,0,0,191,189,1,0,0,0,192,193,3,2,
		1,0,193,199,5,57,0,0,194,197,5,23,0,0,195,198,3,34,17,0,196,198,3,22,11,
		0,197,195,1,0,0,0,197,196,1,0,0,0,198,200,1,0,0,0,199,194,1,0,0,0,199,
		200,1,0,0,0,200,212,1,0,0,0,201,202,5,34,0,0,202,208,5,57,0,0,203,206,
		5,23,0,0,204,207,3,34,17,0,205,207,3,22,11,0,206,204,1,0,0,0,206,205,1,
		0,0,0,207,209,1,0,0,0,208,203,1,0,0,0,208,209,1,0,0,0,209,211,1,0,0,0,
		210,201,1,0,0,0,211,214,1,0,0,0,212,210,1,0,0,0,212,213,1,0,0,0,213,29,
		1,0,0,0,214,212,1,0,0,0,215,216,5,57,0,0,216,217,5,23,0,0,217,238,3,32,
		16,0,218,219,5,57,0,0,219,238,5,24,0,0,220,221,5,57,0,0,221,238,5,25,0,
		0,222,223,5,57,0,0,223,224,5,26,0,0,224,238,3,32,16,0,225,226,5,57,0,0,
		226,227,5,27,0,0,227,238,3,32,16,0,228,229,5,57,0,0,229,230,5,28,0,0,230,
		238,3,32,16,0,231,232,5,57,0,0,232,233,5,29,0,0,233,238,3,32,16,0,234,
		235,5,57,0,0,235,236,5,30,0,0,236,238,3,32,16,0,237,215,1,0,0,0,237,218,
		1,0,0,0,237,220,1,0,0,0,237,222,1,0,0,0,237,225,1,0,0,0,237,228,1,0,0,
		0,237,231,1,0,0,0,237,234,1,0,0,0,238,31,1,0,0,0,239,242,3,34,17,0,240,
		242,3,22,11,0,241,239,1,0,0,0,241,240,1,0,0,0,242,33,1,0,0,0,243,244,6,
		17,-1,0,244,247,3,36,18,0,245,247,3,44,22,0,246,243,1,0,0,0,246,245,1,
		0,0,0,247,256,1,0,0,0,248,249,10,4,0,0,249,250,7,3,0,0,250,255,3,34,17,
		5,251,252,10,3,0,0,252,253,7,4,0,0,253,255,3,34,17,4,254,248,1,0,0,0,254,
		251,1,0,0,0,255,258,1,0,0,0,256,254,1,0,0,0,256,257,1,0,0,0,257,35,1,0,
		0,0,258,256,1,0,0,0,259,266,3,20,10,0,260,266,5,57,0,0,261,262,5,31,0,
		0,262,263,3,34,17,0,263,264,5,32,0,0,264,266,1,0,0,0,265,259,1,0,0,0,265,
		260,1,0,0,0,265,261,1,0,0,0,266,37,1,0,0,0,267,268,7,5,0,0,268,39,1,0,
		0,0,269,270,7,6,0,0,270,41,1,0,0,0,271,272,7,7,0,0,272,43,1,0,0,0,273,
		274,7,8,0,0,274,283,5,31,0,0,275,280,3,18,9,0,276,277,5,34,0,0,277,279,
		3,18,9,0,278,276,1,0,0,0,279,282,1,0,0,0,280,278,1,0,0,0,280,281,1,0,0,
		0,281,284,1,0,0,0,282,280,1,0,0,0,283,275,1,0,0,0,283,284,1,0,0,0,284,
		285,1,0,0,0,285,286,5,32,0,0,286,45,1,0,0,0,287,288,5,14,0,0,288,289,5,
		52,0,0,289,290,5,31,0,0,290,291,5,32,0,0,291,295,5,36,0,0,292,294,3,8,
		4,0,293,292,1,0,0,0,294,297,1,0,0,0,295,293,1,0,0,0,295,296,1,0,0,0,296,
		298,1,0,0,0,297,295,1,0,0,0,298,299,5,37,0,0,299,47,1,0,0,0,31,51,58,86,
		96,105,109,114,118,122,129,137,144,151,157,167,182,189,197,199,206,208,
		212,237,241,246,254,256,265,280,283,295
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
