//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/Users/PC/Desktop/ProjectsAn2/LFC/ANTLRTest/ANTLRTest/Compiler.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


namespace ANTLRTest;


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ICompilerListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class CompilerBaseListener : ICompilerListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] CompilerParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] CompilerParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.globalDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGlobalDeclaration([NotNull] CompilerParser.GlobalDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.globalDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGlobalDeclaration([NotNull] CompilerParser.GlobalDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.functionDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionDeclaration([NotNull] CompilerParser.FunctionDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.functionDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionDeclaration([NotNull] CompilerParser.FunctionDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterList([NotNull] CompilerParser.ParameterListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterList([NotNull] CompilerParser.ParameterListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter([NotNull] CompilerParser.ParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter([NotNull] CompilerParser.ParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.varType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarType([NotNull] CompilerParser.VarTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.varType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarType([NotNull] CompilerParser.VarTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.numericType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumericType([NotNull] CompilerParser.NumericTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.numericType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumericType([NotNull] CompilerParser.NumericTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.stringType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringType([NotNull] CompilerParser.StringTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.stringType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringType([NotNull] CompilerParser.StringTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] CompilerParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] CompilerParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] CompilerParser.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] CompilerParser.IfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.forStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForStatement([NotNull] CompilerParser.ForStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.forStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForStatement([NotNull] CompilerParser.ForStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.whileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileStatement([NotNull] CompilerParser.WhileStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.whileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileStatement([NotNull] CompilerParser.WhileStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStatement([NotNull] CompilerParser.ReturnStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStatement([NotNull] CompilerParser.ReturnStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] CompilerParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] CompilerParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] CompilerParser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] CompilerParser.NumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString([NotNull] CompilerParser.StringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString([NotNull] CompilerParser.StringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.singleLogicalExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSingleLogicalExpr([NotNull] CompilerParser.SingleLogicalExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.singleLogicalExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSingleLogicalExpr([NotNull] CompilerParser.SingleLogicalExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.logicalExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalExpr([NotNull] CompilerParser.LogicalExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.logicalExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalExpr([NotNull] CompilerParser.LogicalExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.varDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarDeclaration([NotNull] CompilerParser.VarDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.varDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarDeclaration([NotNull] CompilerParser.VarDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.varAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarAssignment([NotNull] CompilerParser.VarAssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.varAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarAssignment([NotNull] CompilerParser.VarAssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.varValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarValue([NotNull] CompilerParser.VarValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.varValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarValue([NotNull] CompilerParser.VarValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>MulDivExpr</c>
	/// labeled alternative in <see cref="CompilerParser.arithmExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMulDivExpr([NotNull] CompilerParser.MulDivExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MulDivExpr</c>
	/// labeled alternative in <see cref="CompilerParser.arithmExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMulDivExpr([NotNull] CompilerParser.MulDivExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AtomExpr</c>
	/// labeled alternative in <see cref="CompilerParser.arithmExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtomExpr([NotNull] CompilerParser.AtomExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AtomExpr</c>
	/// labeled alternative in <see cref="CompilerParser.arithmExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtomExpr([NotNull] CompilerParser.AtomExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AddSubExpr</c>
	/// labeled alternative in <see cref="CompilerParser.arithmExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddSubExpr([NotNull] CompilerParser.AddSubExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AddSubExpr</c>
	/// labeled alternative in <see cref="CompilerParser.arithmExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddSubExpr([NotNull] CompilerParser.AddSubExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NumberAtom</c>
	/// labeled alternative in <see cref="CompilerParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumberAtom([NotNull] CompilerParser.NumberAtomContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NumberAtom</c>
	/// labeled alternative in <see cref="CompilerParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumberAtom([NotNull] CompilerParser.NumberAtomContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>IdAtom</c>
	/// labeled alternative in <see cref="CompilerParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdAtom([NotNull] CompilerParser.IdAtomContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>IdAtom</c>
	/// labeled alternative in <see cref="CompilerParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdAtom([NotNull] CompilerParser.IdAtomContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ParenExpr</c>
	/// labeled alternative in <see cref="CompilerParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParenExpr([NotNull] CompilerParser.ParenExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ParenExpr</c>
	/// labeled alternative in <see cref="CompilerParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParenExpr([NotNull] CompilerParser.ParenExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>FuncCallAtom</c>
	/// labeled alternative in <see cref="CompilerParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncCallAtom([NotNull] CompilerParser.FuncCallAtomContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>FuncCallAtom</c>
	/// labeled alternative in <see cref="CompilerParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncCallAtom([NotNull] CompilerParser.FuncCallAtomContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.arithmOperation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArithmOperation([NotNull] CompilerParser.ArithmOperationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.arithmOperation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArithmOperation([NotNull] CompilerParser.ArithmOperationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.comparators"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparators([NotNull] CompilerParser.ComparatorsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.comparators"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparators([NotNull] CompilerParser.ComparatorsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.logicalOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalOp([NotNull] CompilerParser.LogicalOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.logicalOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalOp([NotNull] CompilerParser.LogicalOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionCall([NotNull] CompilerParser.FunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionCall([NotNull] CompilerParser.FunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.mainFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMainFunction([NotNull] CompilerParser.MainFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.mainFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMainFunction([NotNull] CompilerParser.MainFunctionContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
