//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/Users/PC/Desktop/ProjectsAn2/LFC/ANTLRTest/ANTLRTest/Compiler.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


namespace ANTLRTest;

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CompilerParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface ICompilerListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] CompilerParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] CompilerParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.globalDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGlobalDeclaration([NotNull] CompilerParser.GlobalDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.globalDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGlobalDeclaration([NotNull] CompilerParser.GlobalDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.functionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDeclaration([NotNull] CompilerParser.FunctionDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.functionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDeclaration([NotNull] CompilerParser.FunctionDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterList([NotNull] CompilerParser.ParameterListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterList([NotNull] CompilerParser.ParameterListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter([NotNull] CompilerParser.ParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter([NotNull] CompilerParser.ParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.varType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarType([NotNull] CompilerParser.VarTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.varType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarType([NotNull] CompilerParser.VarTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.numericType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumericType([NotNull] CompilerParser.NumericTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.numericType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumericType([NotNull] CompilerParser.NumericTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.stringType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringType([NotNull] CompilerParser.StringTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.stringType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringType([NotNull] CompilerParser.StringTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] CompilerParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] CompilerParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] CompilerParser.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] CompilerParser.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForStatement([NotNull] CompilerParser.ForStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForStatement([NotNull] CompilerParser.ForStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileStatement([NotNull] CompilerParser.WhileStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileStatement([NotNull] CompilerParser.WhileStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStatement([NotNull] CompilerParser.ReturnStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStatement([NotNull] CompilerParser.ReturnStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] CompilerParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] CompilerParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] CompilerParser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] CompilerParser.NumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString([NotNull] CompilerParser.StringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString([NotNull] CompilerParser.StringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.singleLogicalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSingleLogicalExpr([NotNull] CompilerParser.SingleLogicalExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.singleLogicalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSingleLogicalExpr([NotNull] CompilerParser.SingleLogicalExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.logicalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalExpr([NotNull] CompilerParser.LogicalExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.logicalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalExpr([NotNull] CompilerParser.LogicalExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.varDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarDeclaration([NotNull] CompilerParser.VarDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.varDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarDeclaration([NotNull] CompilerParser.VarDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.varAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarAssignment([NotNull] CompilerParser.VarAssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.varAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarAssignment([NotNull] CompilerParser.VarAssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.varValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarValue([NotNull] CompilerParser.VarValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.varValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarValue([NotNull] CompilerParser.VarValueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MulDivExpr</c>
	/// labeled alternative in <see cref="CompilerParser.arithmExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMulDivExpr([NotNull] CompilerParser.MulDivExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MulDivExpr</c>
	/// labeled alternative in <see cref="CompilerParser.arithmExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMulDivExpr([NotNull] CompilerParser.MulDivExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AtomExpr</c>
	/// labeled alternative in <see cref="CompilerParser.arithmExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtomExpr([NotNull] CompilerParser.AtomExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AtomExpr</c>
	/// labeled alternative in <see cref="CompilerParser.arithmExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtomExpr([NotNull] CompilerParser.AtomExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AddSubExpr</c>
	/// labeled alternative in <see cref="CompilerParser.arithmExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddSubExpr([NotNull] CompilerParser.AddSubExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AddSubExpr</c>
	/// labeled alternative in <see cref="CompilerParser.arithmExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddSubExpr([NotNull] CompilerParser.AddSubExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NumberAtom</c>
	/// labeled alternative in <see cref="CompilerParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumberAtom([NotNull] CompilerParser.NumberAtomContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NumberAtom</c>
	/// labeled alternative in <see cref="CompilerParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumberAtom([NotNull] CompilerParser.NumberAtomContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>IdAtom</c>
	/// labeled alternative in <see cref="CompilerParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdAtom([NotNull] CompilerParser.IdAtomContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>IdAtom</c>
	/// labeled alternative in <see cref="CompilerParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdAtom([NotNull] CompilerParser.IdAtomContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ParenExpr</c>
	/// labeled alternative in <see cref="CompilerParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenExpr([NotNull] CompilerParser.ParenExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ParenExpr</c>
	/// labeled alternative in <see cref="CompilerParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenExpr([NotNull] CompilerParser.ParenExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>FuncCallAtom</c>
	/// labeled alternative in <see cref="CompilerParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncCallAtom([NotNull] CompilerParser.FuncCallAtomContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>FuncCallAtom</c>
	/// labeled alternative in <see cref="CompilerParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncCallAtom([NotNull] CompilerParser.FuncCallAtomContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.arithmOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArithmOperation([NotNull] CompilerParser.ArithmOperationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.arithmOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArithmOperation([NotNull] CompilerParser.ArithmOperationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.comparators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparators([NotNull] CompilerParser.ComparatorsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.comparators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparators([NotNull] CompilerParser.ComparatorsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.logicalOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalOp([NotNull] CompilerParser.LogicalOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.logicalOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalOp([NotNull] CompilerParser.LogicalOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCall([NotNull] CompilerParser.FunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCall([NotNull] CompilerParser.FunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CompilerParser.mainFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMainFunction([NotNull] CompilerParser.MainFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CompilerParser.mainFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMainFunction([NotNull] CompilerParser.MainFunctionContext context);
}
