//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/Users/PC/Desktop/ProjectsAn2/LFC/ANTLRTest/ANTLRTest/Compiler.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


namespace ANTLRTest;

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class CompilerParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		BUILTIN_FUNC=1, SINGLE_LINE_COMMENT=2, MULTI_LINE_COMMENT=3, COMMENT=4, 
		IF_TOKEN=5, ELSE_TOKEN=6, FOR_TOKEN=7, WHILE_TOKEN=8, RETURN_TOKEN=9, 
		FLOAT_DOUBLE_TOKEN=10, INT_TOKEN=11, STRING_TOKEN=12, WS=13, INT_TYPE=14, 
		DOUBLE_TYPE=15, FLOAT_TYPE=16, STRING_TYPE=17, PLUS=18, MINUS=19, MUL=20, 
		DIV=21, MOD=22, ASSIGN=23, INCR=24, DECR=25, PLUS_EQ=26, MINUS_EQ=27, 
		MUL_EQ=28, DIV_EQ=29, MOD_EQ=30, LPAREN=31, RPAREN=32, SEMICOL=33, COMMA=34, 
		DOT=35, LBRACE=36, RBRACE=37, LBRACK=38, RBRACK=39, LT=40, LEQ=41, GT=42, 
		GEQ=43, EQ=44, NEQ=45, DQUOTE=46, BINARY_LOGICAL_OP=47, UNARY_LOGICAL_OP=48, 
		TRUE=49, FALSE=50, NULL=51, MAIN=52, SQRT=53, LOG=54, SIN=55, COS=56, 
		ID=57;
	public const int
		RULE_program = 0, RULE_globalDeclaration = 1, RULE_functionDeclaration = 2, 
		RULE_parameterList = 3, RULE_parameter = 4, RULE_varType = 5, RULE_numericType = 6, 
		RULE_stringType = 7, RULE_statement = 8, RULE_ifStatement = 9, RULE_forStatement = 10, 
		RULE_whileStatement = 11, RULE_returnStatement = 12, RULE_expression = 13, 
		RULE_number = 14, RULE_string = 15, RULE_singleLogicalExpr = 16, RULE_logicalExpr = 17, 
		RULE_varDeclaration = 18, RULE_varAssignment = 19, RULE_varValue = 20, 
		RULE_arithmExpr = 21, RULE_atom = 22, RULE_arithmOperation = 23, RULE_comparators = 24, 
		RULE_logicalOp = 25, RULE_functionCall = 26, RULE_mainFunction = 27;
	public static readonly string[] ruleNames = {
		"program", "globalDeclaration", "functionDeclaration", "parameterList", 
		"parameter", "varType", "numericType", "stringType", "statement", "ifStatement", 
		"forStatement", "whileStatement", "returnStatement", "expression", "number", 
		"string", "singleLogicalExpr", "logicalExpr", "varDeclaration", "varAssignment", 
		"varValue", "arithmExpr", "atom", "arithmOperation", "comparators", "logicalOp", 
		"functionCall", "mainFunction"
	};

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, "'if'", "'else'", "'for'", "'while'", "'return'", 
		null, null, null, null, "'int'", "'double'", "'float'", "'string'", "'+'", 
		"'-'", "'*'", "'/'", "'%'", "'='", "'++'", "'--'", "'+='", "'-='", "'*='", 
		"'/='", "'%='", "'('", "')'", "';'", "','", "'.'", "'{'", "'}'", "'['", 
		"']'", "'<'", "'<='", "'>'", "'>='", "'=='", "'!='", "'\"'", null, "'!'", 
		"'true'", "'false'", "'null'", "'main'", "'sqrt'", "'log'", "'sin'", "'cos'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "BUILTIN_FUNC", "SINGLE_LINE_COMMENT", "MULTI_LINE_COMMENT", "COMMENT", 
		"IF_TOKEN", "ELSE_TOKEN", "FOR_TOKEN", "WHILE_TOKEN", "RETURN_TOKEN", 
		"FLOAT_DOUBLE_TOKEN", "INT_TOKEN", "STRING_TOKEN", "WS", "INT_TYPE", "DOUBLE_TYPE", 
		"FLOAT_TYPE", "STRING_TYPE", "PLUS", "MINUS", "MUL", "DIV", "MOD", "ASSIGN", 
		"INCR", "DECR", "PLUS_EQ", "MINUS_EQ", "MUL_EQ", "DIV_EQ", "MOD_EQ", "LPAREN", 
		"RPAREN", "SEMICOL", "COMMA", "DOT", "LBRACE", "RBRACE", "LBRACK", "RBRACK", 
		"LT", "LEQ", "GT", "GEQ", "EQ", "NEQ", "DQUOTE", "BINARY_LOGICAL_OP", 
		"UNARY_LOGICAL_OP", "TRUE", "FALSE", "NULL", "MAIN", "SQRT", "LOG", "SIN", 
		"COS", "ID"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Compiler.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static CompilerParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public CompilerParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public CompilerParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public MainFunctionContext mainFunction() {
			return GetRuleContext<MainFunctionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(CompilerParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public GlobalDeclarationContext[] globalDeclaration() {
			return GetRuleContexts<GlobalDeclarationContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public GlobalDeclarationContext globalDeclaration(int i) {
			return GetRuleContext<GlobalDeclarationContext>(i);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 59;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,0,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 56;
					globalDeclaration();
					}
					} 
				}
				State = 61;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,0,Context);
			}
			State = 62;
			mainFunction();
			State = 63;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class GlobalDeclarationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public VarDeclarationContext varDeclaration() {
			return GetRuleContext<VarDeclarationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOL() { return GetToken(CompilerParser.SEMICOL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public FunctionDeclarationContext functionDeclaration() {
			return GetRuleContext<FunctionDeclarationContext>(0);
		}
		public GlobalDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_globalDeclaration; } }
	}

	[RuleVersion(0)]
	public GlobalDeclarationContext globalDeclaration() {
		GlobalDeclarationContext _localctx = new GlobalDeclarationContext(Context, State);
		EnterRule(_localctx, 2, RULE_globalDeclaration);
		try {
			State = 69;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,1,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 65;
				varDeclaration();
				State = 66;
				Match(SEMICOL);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 68;
				functionDeclaration();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionDeclarationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public VarTypeContext varType() {
			return GetRuleContext<VarTypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(CompilerParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(CompilerParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(CompilerParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(CompilerParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(CompilerParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ParameterListContext parameterList() {
			return GetRuleContext<ParameterListContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public FunctionDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionDeclaration; } }
	}

	[RuleVersion(0)]
	public FunctionDeclarationContext functionDeclaration() {
		FunctionDeclarationContext _localctx = new FunctionDeclarationContext(Context, State);
		EnterRule(_localctx, 4, RULE_functionDeclaration);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 71;
			varType();
			State = 72;
			Match(ID);
			State = 73;
			Match(LPAREN);
			State = 75;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 245760L) != 0)) {
				{
				State = 74;
				parameterList();
				}
			}

			State = 77;
			Match(RPAREN);
			State = 78;
			Match(LBRACE);
			State = 82;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 144115198813523874L) != 0)) {
				{
				{
				State = 79;
				statement();
				}
				}
				State = 84;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 85;
			Match(RBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ParameterListContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ParameterContext[] parameter() {
			return GetRuleContexts<ParameterContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ParameterContext parameter(int i) {
			return GetRuleContext<ParameterContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(CompilerParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(CompilerParser.COMMA, i);
		}
		public ParameterListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_parameterList; } }
	}

	[RuleVersion(0)]
	public ParameterListContext parameterList() {
		ParameterListContext _localctx = new ParameterListContext(Context, State);
		EnterRule(_localctx, 6, RULE_parameterList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 87;
			parameter();
			State = 92;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 88;
				Match(COMMA);
				State = 89;
				parameter();
				}
				}
				State = 94;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ParameterContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public VarTypeContext varType() {
			return GetRuleContext<VarTypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(CompilerParser.ID, 0); }
		public ParameterContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_parameter; } }
	}

	[RuleVersion(0)]
	public ParameterContext parameter() {
		ParameterContext _localctx = new ParameterContext(Context, State);
		EnterRule(_localctx, 8, RULE_parameter);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 95;
			varType();
			State = 96;
			Match(ID);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VarTypeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT_TYPE() { return GetToken(CompilerParser.INT_TYPE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOUBLE_TYPE() { return GetToken(CompilerParser.DOUBLE_TYPE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FLOAT_TYPE() { return GetToken(CompilerParser.FLOAT_TYPE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING_TYPE() { return GetToken(CompilerParser.STRING_TYPE, 0); }
		public VarTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_varType; } }
	}

	[RuleVersion(0)]
	public VarTypeContext varType() {
		VarTypeContext _localctx = new VarTypeContext(Context, State);
		EnterRule(_localctx, 10, RULE_varType);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 98;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 245760L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumericTypeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT_TYPE() { return GetToken(CompilerParser.INT_TYPE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOUBLE_TYPE() { return GetToken(CompilerParser.DOUBLE_TYPE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FLOAT_TYPE() { return GetToken(CompilerParser.FLOAT_TYPE, 0); }
		public NumericTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_numericType; } }
	}

	[RuleVersion(0)]
	public NumericTypeContext numericType() {
		NumericTypeContext _localctx = new NumericTypeContext(Context, State);
		EnterRule(_localctx, 12, RULE_numericType);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 100;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 114688L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StringTypeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING_TYPE() { return GetToken(CompilerParser.STRING_TYPE, 0); }
		public StringTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stringType; } }
	}

	[RuleVersion(0)]
	public StringTypeContext stringType() {
		StringTypeContext _localctx = new StringTypeContext(Context, State);
		EnterRule(_localctx, 14, RULE_stringType);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 102;
			Match(STRING_TYPE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOL() { return GetToken(CompilerParser.SEMICOL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public VarDeclarationContext varDeclaration() {
			return GetRuleContext<VarDeclarationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public VarAssignmentContext varAssignment() {
			return GetRuleContext<VarAssignmentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext arithmExpr() {
			return GetRuleContext<ArithmExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IfStatementContext ifStatement() {
			return GetRuleContext<IfStatementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ForStatementContext forStatement() {
			return GetRuleContext<ForStatementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public WhileStatementContext whileStatement() {
			return GetRuleContext<WhileStatementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ReturnStatementContext returnStatement() {
			return GetRuleContext<ReturnStatementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionCallContext functionCall() {
			return GetRuleContext<FunctionCallContext>(0);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 16, RULE_statement);
		try {
			State = 121;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,5,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 104;
				Match(SEMICOL);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 105;
				varDeclaration();
				State = 106;
				Match(SEMICOL);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 108;
				varAssignment();
				State = 109;
				Match(SEMICOL);
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 111;
				arithmExpr(0);
				State = 112;
				Match(SEMICOL);
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 114;
				ifStatement();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 115;
				forStatement();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 116;
				whileStatement();
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 117;
				returnStatement();
				}
				break;
			case 9:
				EnterOuterAlt(_localctx, 9);
				{
				State = 118;
				functionCall();
				State = 119;
				Match(SEMICOL);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IfStatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IF_TOKEN() { return GetToken(CompilerParser.IF_TOKEN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(CompilerParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public LogicalExprContext logicalExpr() {
			return GetRuleContext<LogicalExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(CompilerParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] LBRACE() { return GetTokens(CompilerParser.LBRACE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE(int i) {
			return GetToken(CompilerParser.LBRACE, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] RBRACE() { return GetTokens(CompilerParser.RBRACE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE(int i) {
			return GetToken(CompilerParser.RBRACE, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ELSE_TOKEN() { return GetToken(CompilerParser.ELSE_TOKEN, 0); }
		public IfStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ifStatement; } }
	}

	[RuleVersion(0)]
	public IfStatementContext ifStatement() {
		IfStatementContext _localctx = new IfStatementContext(Context, State);
		EnterRule(_localctx, 18, RULE_ifStatement);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 123;
			Match(IF_TOKEN);
			State = 124;
			Match(LPAREN);
			State = 125;
			logicalExpr();
			State = 126;
			Match(RPAREN);
			State = 127;
			Match(LBRACE);
			State = 131;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 144115198813523874L) != 0)) {
				{
				{
				State = 128;
				statement();
				}
				}
				State = 133;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 134;
			Match(RBRACE);
			State = 144;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ELSE_TOKEN) {
				{
				State = 135;
				Match(ELSE_TOKEN);
				State = 136;
				Match(LBRACE);
				State = 140;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 144115198813523874L) != 0)) {
					{
					{
					State = 137;
					statement();
					}
					}
					State = 142;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 143;
				Match(RBRACE);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ForStatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FOR_TOKEN() { return GetToken(CompilerParser.FOR_TOKEN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(CompilerParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SEMICOL() { return GetTokens(CompilerParser.SEMICOL); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOL(int i) {
			return GetToken(CompilerParser.SEMICOL, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(CompilerParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(CompilerParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(CompilerParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public VarDeclarationContext varDeclaration() {
			return GetRuleContext<VarDeclarationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public LogicalExprContext logicalExpr() {
			return GetRuleContext<LogicalExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public VarAssignmentContext varAssignment() {
			return GetRuleContext<VarAssignmentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public ForStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_forStatement; } }
	}

	[RuleVersion(0)]
	public ForStatementContext forStatement() {
		ForStatementContext _localctx = new ForStatementContext(Context, State);
		EnterRule(_localctx, 20, RULE_forStatement);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 146;
			Match(FOR_TOKEN);
			State = 147;
			Match(LPAREN);
			State = 149;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 245760L) != 0)) {
				{
				State = 148;
				varDeclaration();
				}
			}

			State = 151;
			Match(SEMICOL);
			State = 153;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 148337314874002434L) != 0)) {
				{
				State = 152;
				logicalExpr();
				}
			}

			State = 155;
			Match(SEMICOL);
			State = 157;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ID) {
				{
				State = 156;
				varAssignment();
				}
			}

			State = 159;
			Match(RPAREN);
			State = 160;
			Match(LBRACE);
			State = 164;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 144115198813523874L) != 0)) {
				{
				{
				State = 161;
				statement();
				}
				}
				State = 166;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 167;
			Match(RBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class WhileStatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WHILE_TOKEN() { return GetToken(CompilerParser.WHILE_TOKEN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(CompilerParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(CompilerParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(CompilerParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(CompilerParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public LogicalExprContext logicalExpr() {
			return GetRuleContext<LogicalExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public WhileStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_whileStatement; } }
	}

	[RuleVersion(0)]
	public WhileStatementContext whileStatement() {
		WhileStatementContext _localctx = new WhileStatementContext(Context, State);
		EnterRule(_localctx, 22, RULE_whileStatement);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 169;
			Match(WHILE_TOKEN);
			State = 170;
			Match(LPAREN);
			State = 172;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 148337314874002434L) != 0)) {
				{
				State = 171;
				logicalExpr();
				}
			}

			State = 174;
			Match(RPAREN);
			State = 175;
			Match(LBRACE);
			State = 179;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 144115198813523874L) != 0)) {
				{
				{
				State = 176;
				statement();
				}
				}
				State = 181;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 182;
			Match(RBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ReturnStatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RETURN_TOKEN() { return GetToken(CompilerParser.RETURN_TOKEN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOL() { return GetToken(CompilerParser.SEMICOL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ReturnStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_returnStatement; } }
	}

	[RuleVersion(0)]
	public ReturnStatementContext returnStatement() {
		ReturnStatementContext _localctx = new ReturnStatementContext(Context, State);
		EnterRule(_localctx, 24, RULE_returnStatement);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 184;
			Match(RETURN_TOKEN);
			State = 186;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 144115190223346690L) != 0)) {
				{
				State = 185;
				expression();
				}
			}

			State = 188;
			Match(SEMICOL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext arithmExpr() {
			return GetRuleContext<ArithmExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StringContext @string() {
			return GetRuleContext<StringContext>(0);
		}
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		ExpressionContext _localctx = new ExpressionContext(Context, State);
		EnterRule(_localctx, 26, RULE_expression);
		try {
			State = 192;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case BUILTIN_FUNC:
			case FLOAT_DOUBLE_TOKEN:
			case INT_TOKEN:
			case LPAREN:
			case ID:
				EnterOuterAlt(_localctx, 1);
				{
				State = 190;
				arithmExpr(0);
				}
				break;
			case STRING_TOKEN:
				EnterOuterAlt(_localctx, 2);
				{
				State = 191;
				@string();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumberContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FLOAT_DOUBLE_TOKEN() { return GetToken(CompilerParser.FLOAT_DOUBLE_TOKEN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT_TOKEN() { return GetToken(CompilerParser.INT_TOKEN, 0); }
		public NumberContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_number; } }
	}

	[RuleVersion(0)]
	public NumberContext number() {
		NumberContext _localctx = new NumberContext(Context, State);
		EnterRule(_localctx, 28, RULE_number);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 194;
			_la = TokenStream.LA(1);
			if ( !(_la==FLOAT_DOUBLE_TOKEN || _la==INT_TOKEN) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StringContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING_TOKEN() { return GetToken(CompilerParser.STRING_TOKEN, 0); }
		public StringContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_string; } }
	}

	[RuleVersion(0)]
	public StringContext @string() {
		StringContext _localctx = new StringContext(Context, State);
		EnterRule(_localctx, 30, RULE_string);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 196;
			Match(STRING_TOKEN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SingleLogicalExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext[] arithmExpr() {
			return GetRuleContexts<ArithmExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext arithmExpr(int i) {
			return GetRuleContext<ArithmExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ComparatorsContext comparators() {
			return GetRuleContext<ComparatorsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(CompilerParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public LogicalExprContext logicalExpr() {
			return GetRuleContext<LogicalExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(CompilerParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode UNARY_LOGICAL_OP() { return GetToken(CompilerParser.UNARY_LOGICAL_OP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public SingleLogicalExprContext singleLogicalExpr() {
			return GetRuleContext<SingleLogicalExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(CompilerParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StringContext @string() {
			return GetRuleContext<StringContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TRUE() { return GetToken(CompilerParser.TRUE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FALSE() { return GetToken(CompilerParser.FALSE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NULL() { return GetToken(CompilerParser.NULL, 0); }
		public SingleLogicalExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_singleLogicalExpr; } }
	}

	[RuleVersion(0)]
	public SingleLogicalExprContext singleLogicalExpr() {
		SingleLogicalExprContext _localctx = new SingleLogicalExprContext(Context, State);
		EnterRule(_localctx, 32, RULE_singleLogicalExpr);
		int _la;
		try {
			State = 217;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,18,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 198;
				arithmExpr(0);
				State = 202;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 69269232549888L) != 0)) {
					{
					State = 199;
					comparators();
					State = 200;
					arithmExpr(0);
					}
				}

				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 204;
				Match(LPAREN);
				State = 205;
				logicalExpr();
				State = 206;
				Match(RPAREN);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 208;
				Match(UNARY_LOGICAL_OP);
				State = 209;
				singleLogicalExpr();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 210;
				Match(ID);
				State = 211;
				comparators();
				State = 212;
				@string();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 214;
				Match(TRUE);
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 215;
				Match(FALSE);
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 216;
				Match(NULL);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LogicalExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SingleLogicalExprContext singleLogicalExpr() {
			return GetRuleContext<SingleLogicalExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] BINARY_LOGICAL_OP() { return GetTokens(CompilerParser.BINARY_LOGICAL_OP); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BINARY_LOGICAL_OP(int i) {
			return GetToken(CompilerParser.BINARY_LOGICAL_OP, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public LogicalExprContext[] logicalExpr() {
			return GetRuleContexts<LogicalExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public LogicalExprContext logicalExpr(int i) {
			return GetRuleContext<LogicalExprContext>(i);
		}
		public LogicalExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_logicalExpr; } }
	}

	[RuleVersion(0)]
	public LogicalExprContext logicalExpr() {
		LogicalExprContext _localctx = new LogicalExprContext(Context, State);
		EnterRule(_localctx, 34, RULE_logicalExpr);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 219;
			singleLogicalExpr();
			State = 224;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,19,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 220;
					Match(BINARY_LOGICAL_OP);
					State = 221;
					logicalExpr();
					}
					} 
				}
				State = 226;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,19,Context);
			}
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VarDeclarationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public VarTypeContext varType() {
			return GetRuleContext<VarTypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ID() { return GetTokens(CompilerParser.ID); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID(int i) {
			return GetToken(CompilerParser.ID, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ASSIGN() { return GetTokens(CompilerParser.ASSIGN); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN(int i) {
			return GetToken(CompilerParser.ASSIGN, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(CompilerParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(CompilerParser.COMMA, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext[] arithmExpr() {
			return GetRuleContexts<ArithmExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext arithmExpr(int i) {
			return GetRuleContext<ArithmExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StringContext[] @string() {
			return GetRuleContexts<StringContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StringContext @string(int i) {
			return GetRuleContext<StringContext>(i);
		}
		public VarDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_varDeclaration; } }
	}

	[RuleVersion(0)]
	public VarDeclarationContext varDeclaration() {
		VarDeclarationContext _localctx = new VarDeclarationContext(Context, State);
		EnterRule(_localctx, 36, RULE_varDeclaration);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 227;
			varType();
			{
			State = 228;
			Match(ID);
			State = 234;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ASSIGN) {
				{
				State = 229;
				Match(ASSIGN);
				State = 232;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case BUILTIN_FUNC:
				case FLOAT_DOUBLE_TOKEN:
				case INT_TOKEN:
				case LPAREN:
				case ID:
					{
					State = 230;
					arithmExpr(0);
					}
					break;
				case STRING_TOKEN:
					{
					State = 231;
					@string();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
			}

			State = 247;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 236;
				Match(COMMA);
				State = 237;
				Match(ID);
				State = 243;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==ASSIGN) {
					{
					State = 238;
					Match(ASSIGN);
					State = 241;
					ErrorHandler.Sync(this);
					switch (TokenStream.LA(1)) {
					case BUILTIN_FUNC:
					case FLOAT_DOUBLE_TOKEN:
					case INT_TOKEN:
					case LPAREN:
					case ID:
						{
						State = 239;
						arithmExpr(0);
						}
						break;
					case STRING_TOKEN:
						{
						State = 240;
						@string();
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					}
				}

				}
				}
				State = 249;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VarAssignmentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(CompilerParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN() { return GetToken(CompilerParser.ASSIGN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public VarValueContext varValue() {
			return GetRuleContext<VarValueContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INCR() { return GetToken(CompilerParser.INCR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DECR() { return GetToken(CompilerParser.DECR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUS_EQ() { return GetToken(CompilerParser.PLUS_EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS_EQ() { return GetToken(CompilerParser.MINUS_EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MUL_EQ() { return GetToken(CompilerParser.MUL_EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIV_EQ() { return GetToken(CompilerParser.DIV_EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MOD_EQ() { return GetToken(CompilerParser.MOD_EQ, 0); }
		public VarAssignmentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_varAssignment; } }
	}

	[RuleVersion(0)]
	public VarAssignmentContext varAssignment() {
		VarAssignmentContext _localctx = new VarAssignmentContext(Context, State);
		EnterRule(_localctx, 38, RULE_varAssignment);
		try {
			State = 272;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,25,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 250;
				Match(ID);
				State = 251;
				Match(ASSIGN);
				State = 252;
				varValue();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 253;
				Match(ID);
				State = 254;
				Match(INCR);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 255;
				Match(ID);
				State = 256;
				Match(DECR);
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 257;
				Match(ID);
				State = 258;
				Match(PLUS_EQ);
				State = 259;
				varValue();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 260;
				Match(ID);
				State = 261;
				Match(MINUS_EQ);
				State = 262;
				varValue();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 263;
				Match(ID);
				State = 264;
				Match(MUL_EQ);
				State = 265;
				varValue();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 266;
				Match(ID);
				State = 267;
				Match(DIV_EQ);
				State = 268;
				varValue();
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 269;
				Match(ID);
				State = 270;
				Match(MOD_EQ);
				State = 271;
				varValue();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VarValueContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext arithmExpr() {
			return GetRuleContext<ArithmExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StringContext @string() {
			return GetRuleContext<StringContext>(0);
		}
		public VarValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_varValue; } }
	}

	[RuleVersion(0)]
	public VarValueContext varValue() {
		VarValueContext _localctx = new VarValueContext(Context, State);
		EnterRule(_localctx, 40, RULE_varValue);
		try {
			State = 276;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case BUILTIN_FUNC:
			case FLOAT_DOUBLE_TOKEN:
			case INT_TOKEN:
			case LPAREN:
			case ID:
				EnterOuterAlt(_localctx, 1);
				{
				State = 274;
				arithmExpr(0);
				}
				break;
			case STRING_TOKEN:
				EnterOuterAlt(_localctx, 2);
				{
				State = 275;
				@string();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArithmExprContext : ParserRuleContext {
		public ArithmExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arithmExpr; } }
	 
		public ArithmExprContext() { }
		public virtual void CopyFrom(ArithmExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class MulDivExprContext : ArithmExprContext {
		public IToken op;
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext[] arithmExpr() {
			return GetRuleContexts<ArithmExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext arithmExpr(int i) {
			return GetRuleContext<ArithmExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MUL() { return GetToken(CompilerParser.MUL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIV() { return GetToken(CompilerParser.DIV, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MOD() { return GetToken(CompilerParser.MOD, 0); }
		public MulDivExprContext(ArithmExprContext context) { CopyFrom(context); }
	}
	public partial class AtomExprContext : ArithmExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public AtomContext atom() {
			return GetRuleContext<AtomContext>(0);
		}
		public AtomExprContext(ArithmExprContext context) { CopyFrom(context); }
	}
	public partial class AddSubExprContext : ArithmExprContext {
		public IToken op;
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext[] arithmExpr() {
			return GetRuleContexts<ArithmExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext arithmExpr(int i) {
			return GetRuleContext<ArithmExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUS() { return GetToken(CompilerParser.PLUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS() { return GetToken(CompilerParser.MINUS, 0); }
		public AddSubExprContext(ArithmExprContext context) { CopyFrom(context); }
	}

	[RuleVersion(0)]
	public ArithmExprContext arithmExpr() {
		return arithmExpr(0);
	}

	private ArithmExprContext arithmExpr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ArithmExprContext _localctx = new ArithmExprContext(Context, _parentState);
		ArithmExprContext _prevctx = _localctx;
		int _startState = 42;
		EnterRecursionRule(_localctx, 42, RULE_arithmExpr, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			_localctx = new AtomExprContext(_localctx);
			Context = _localctx;
			_prevctx = _localctx;

			State = 279;
			atom();
			}
			Context.Stop = TokenStream.LT(-1);
			State = 289;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,28,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 287;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,27,Context) ) {
					case 1:
						{
						_localctx = new MulDivExprContext(new ArithmExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_arithmExpr);
						State = 281;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 282;
						((MulDivExprContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 7340032L) != 0)) ) {
							((MulDivExprContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 283;
						arithmExpr(4);
						}
						break;
					case 2:
						{
						_localctx = new AddSubExprContext(new ArithmExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_arithmExpr);
						State = 284;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 285;
						((AddSubExprContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==PLUS || _la==MINUS) ) {
							((AddSubExprContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 286;
						arithmExpr(3);
						}
						break;
					}
					} 
				}
				State = 291;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,28,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class AtomContext : ParserRuleContext {
		public AtomContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_atom; } }
	 
		public AtomContext() { }
		public virtual void CopyFrom(AtomContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class NumberAtomContext : AtomContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberContext number() {
			return GetRuleContext<NumberContext>(0);
		}
		public NumberAtomContext(AtomContext context) { CopyFrom(context); }
	}
	public partial class FuncCallAtomContext : AtomContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionCallContext functionCall() {
			return GetRuleContext<FunctionCallContext>(0);
		}
		public FuncCallAtomContext(AtomContext context) { CopyFrom(context); }
	}
	public partial class ParenExprContext : AtomContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(CompilerParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext arithmExpr() {
			return GetRuleContext<ArithmExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(CompilerParser.RPAREN, 0); }
		public ParenExprContext(AtomContext context) { CopyFrom(context); }
	}
	public partial class IdAtomContext : AtomContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(CompilerParser.ID, 0); }
		public IdAtomContext(AtomContext context) { CopyFrom(context); }
	}

	[RuleVersion(0)]
	public AtomContext atom() {
		AtomContext _localctx = new AtomContext(Context, State);
		EnterRule(_localctx, 44, RULE_atom);
		try {
			State = 299;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,29,Context) ) {
			case 1:
				_localctx = new NumberAtomContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 292;
				number();
				}
				break;
			case 2:
				_localctx = new IdAtomContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 293;
				Match(ID);
				}
				break;
			case 3:
				_localctx = new ParenExprContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 294;
				Match(LPAREN);
				State = 295;
				arithmExpr(0);
				State = 296;
				Match(RPAREN);
				}
				break;
			case 4:
				_localctx = new FuncCallAtomContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 298;
				functionCall();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArithmOperationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUS() { return GetToken(CompilerParser.PLUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS() { return GetToken(CompilerParser.MINUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MUL() { return GetToken(CompilerParser.MUL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIV() { return GetToken(CompilerParser.DIV, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MOD() { return GetToken(CompilerParser.MOD, 0); }
		public ArithmOperationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arithmOperation; } }
	}

	[RuleVersion(0)]
	public ArithmOperationContext arithmOperation() {
		ArithmOperationContext _localctx = new ArithmOperationContext(Context, State);
		EnterRule(_localctx, 46, RULE_arithmOperation);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 301;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 8126464L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ComparatorsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LT() { return GetToken(CompilerParser.LT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LEQ() { return GetToken(CompilerParser.LEQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GT() { return GetToken(CompilerParser.GT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GEQ() { return GetToken(CompilerParser.GEQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQ() { return GetToken(CompilerParser.EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEQ() { return GetToken(CompilerParser.NEQ, 0); }
		public ComparatorsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_comparators; } }
	}

	[RuleVersion(0)]
	public ComparatorsContext comparators() {
		ComparatorsContext _localctx = new ComparatorsContext(Context, State);
		EnterRule(_localctx, 48, RULE_comparators);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 303;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 69269232549888L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LogicalOpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BINARY_LOGICAL_OP() { return GetToken(CompilerParser.BINARY_LOGICAL_OP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode UNARY_LOGICAL_OP() { return GetToken(CompilerParser.UNARY_LOGICAL_OP, 0); }
		public LogicalOpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_logicalOp; } }
	}

	[RuleVersion(0)]
	public LogicalOpContext logicalOp() {
		LogicalOpContext _localctx = new LogicalOpContext(Context, State);
		EnterRule(_localctx, 50, RULE_logicalOp);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 305;
			_la = TokenStream.LA(1);
			if ( !(_la==BINARY_LOGICAL_OP || _la==UNARY_LOGICAL_OP) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionCallContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(CompilerParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(CompilerParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(CompilerParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BUILTIN_FUNC() { return GetToken(CompilerParser.BUILTIN_FUNC, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(CompilerParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(CompilerParser.COMMA, i);
		}
		public FunctionCallContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionCall; } }
	}

	[RuleVersion(0)]
	public FunctionCallContext functionCall() {
		FunctionCallContext _localctx = new FunctionCallContext(Context, State);
		EnterRule(_localctx, 52, RULE_functionCall);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 307;
			_la = TokenStream.LA(1);
			if ( !(_la==BUILTIN_FUNC || _la==ID) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 308;
			Match(LPAREN);
			State = 317;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 144115190223346690L) != 0)) {
				{
				State = 309;
				expression();
				State = 314;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==COMMA) {
					{
					{
					State = 310;
					Match(COMMA);
					State = 311;
					expression();
					}
					}
					State = 316;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 319;
			Match(RPAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MainFunctionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT_TYPE() { return GetToken(CompilerParser.INT_TYPE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MAIN() { return GetToken(CompilerParser.MAIN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(CompilerParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(CompilerParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(CompilerParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(CompilerParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public MainFunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_mainFunction; } }
	}

	[RuleVersion(0)]
	public MainFunctionContext mainFunction() {
		MainFunctionContext _localctx = new MainFunctionContext(Context, State);
		EnterRule(_localctx, 54, RULE_mainFunction);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 321;
			Match(INT_TYPE);
			State = 322;
			Match(MAIN);
			State = 323;
			Match(LPAREN);
			State = 324;
			Match(RPAREN);
			State = 325;
			Match(LBRACE);
			State = 329;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 144115198813523874L) != 0)) {
				{
				{
				State = 326;
				statement();
				}
				}
				State = 331;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 332;
			Match(RBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 21: return arithmExpr_sempred((ArithmExprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool arithmExpr_sempred(ArithmExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 3);
		case 1: return Precpred(Context, 2);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,57,335,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,2,23,7,23,2,24,7,24,2,25,7,25,2,26,7,26,2,27,7,27,1,0,5,0,58,
		8,0,10,0,12,0,61,9,0,1,0,1,0,1,0,1,1,1,1,1,1,1,1,3,1,70,8,1,1,2,1,2,1,
		2,1,2,3,2,76,8,2,1,2,1,2,1,2,5,2,81,8,2,10,2,12,2,84,9,2,1,2,1,2,1,3,1,
		3,1,3,5,3,91,8,3,10,3,12,3,94,9,3,1,4,1,4,1,4,1,5,1,5,1,6,1,6,1,7,1,7,
		1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,3,
		8,122,8,8,1,9,1,9,1,9,1,9,1,9,1,9,5,9,130,8,9,10,9,12,9,133,9,9,1,9,1,
		9,1,9,1,9,5,9,139,8,9,10,9,12,9,142,9,9,1,9,3,9,145,8,9,1,10,1,10,1,10,
		3,10,150,8,10,1,10,1,10,3,10,154,8,10,1,10,1,10,3,10,158,8,10,1,10,1,10,
		1,10,5,10,163,8,10,10,10,12,10,166,9,10,1,10,1,10,1,11,1,11,1,11,3,11,
		173,8,11,1,11,1,11,1,11,5,11,178,8,11,10,11,12,11,181,9,11,1,11,1,11,1,
		12,1,12,3,12,187,8,12,1,12,1,12,1,13,1,13,3,13,193,8,13,1,14,1,14,1,15,
		1,15,1,16,1,16,1,16,1,16,3,16,203,8,16,1,16,1,16,1,16,1,16,1,16,1,16,1,
		16,1,16,1,16,1,16,1,16,1,16,1,16,3,16,218,8,16,1,17,1,17,1,17,5,17,223,
		8,17,10,17,12,17,226,9,17,1,18,1,18,1,18,1,18,1,18,3,18,233,8,18,3,18,
		235,8,18,1,18,1,18,1,18,1,18,1,18,3,18,242,8,18,3,18,244,8,18,5,18,246,
		8,18,10,18,12,18,249,9,18,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,
		1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,3,19,
		273,8,19,1,20,1,20,3,20,277,8,20,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,
		21,1,21,5,21,288,8,21,10,21,12,21,291,9,21,1,22,1,22,1,22,1,22,1,22,1,
		22,1,22,3,22,300,8,22,1,23,1,23,1,24,1,24,1,25,1,25,1,26,1,26,1,26,1,26,
		1,26,5,26,313,8,26,10,26,12,26,316,9,26,3,26,318,8,26,1,26,1,26,1,27,1,
		27,1,27,1,27,1,27,1,27,5,27,328,8,27,10,27,12,27,331,9,27,1,27,1,27,1,
		27,0,1,42,28,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,
		42,44,46,48,50,52,54,0,9,1,0,14,17,1,0,14,16,1,0,10,11,1,0,20,22,1,0,18,
		19,1,0,18,22,1,0,40,45,1,0,47,48,2,0,1,1,57,57,359,0,59,1,0,0,0,2,69,1,
		0,0,0,4,71,1,0,0,0,6,87,1,0,0,0,8,95,1,0,0,0,10,98,1,0,0,0,12,100,1,0,
		0,0,14,102,1,0,0,0,16,121,1,0,0,0,18,123,1,0,0,0,20,146,1,0,0,0,22,169,
		1,0,0,0,24,184,1,0,0,0,26,192,1,0,0,0,28,194,1,0,0,0,30,196,1,0,0,0,32,
		217,1,0,0,0,34,219,1,0,0,0,36,227,1,0,0,0,38,272,1,0,0,0,40,276,1,0,0,
		0,42,278,1,0,0,0,44,299,1,0,0,0,46,301,1,0,0,0,48,303,1,0,0,0,50,305,1,
		0,0,0,52,307,1,0,0,0,54,321,1,0,0,0,56,58,3,2,1,0,57,56,1,0,0,0,58,61,
		1,0,0,0,59,57,1,0,0,0,59,60,1,0,0,0,60,62,1,0,0,0,61,59,1,0,0,0,62,63,
		3,54,27,0,63,64,5,0,0,1,64,1,1,0,0,0,65,66,3,36,18,0,66,67,5,33,0,0,67,
		70,1,0,0,0,68,70,3,4,2,0,69,65,1,0,0,0,69,68,1,0,0,0,70,3,1,0,0,0,71,72,
		3,10,5,0,72,73,5,57,0,0,73,75,5,31,0,0,74,76,3,6,3,0,75,74,1,0,0,0,75,
		76,1,0,0,0,76,77,1,0,0,0,77,78,5,32,0,0,78,82,5,36,0,0,79,81,3,16,8,0,
		80,79,1,0,0,0,81,84,1,0,0,0,82,80,1,0,0,0,82,83,1,0,0,0,83,85,1,0,0,0,
		84,82,1,0,0,0,85,86,5,37,0,0,86,5,1,0,0,0,87,92,3,8,4,0,88,89,5,34,0,0,
		89,91,3,8,4,0,90,88,1,0,0,0,91,94,1,0,0,0,92,90,1,0,0,0,92,93,1,0,0,0,
		93,7,1,0,0,0,94,92,1,0,0,0,95,96,3,10,5,0,96,97,5,57,0,0,97,9,1,0,0,0,
		98,99,7,0,0,0,99,11,1,0,0,0,100,101,7,1,0,0,101,13,1,0,0,0,102,103,5,17,
		0,0,103,15,1,0,0,0,104,122,5,33,0,0,105,106,3,36,18,0,106,107,5,33,0,0,
		107,122,1,0,0,0,108,109,3,38,19,0,109,110,5,33,0,0,110,122,1,0,0,0,111,
		112,3,42,21,0,112,113,5,33,0,0,113,122,1,0,0,0,114,122,3,18,9,0,115,122,
		3,20,10,0,116,122,3,22,11,0,117,122,3,24,12,0,118,119,3,52,26,0,119,120,
		5,33,0,0,120,122,1,0,0,0,121,104,1,0,0,0,121,105,1,0,0,0,121,108,1,0,0,
		0,121,111,1,0,0,0,121,114,1,0,0,0,121,115,1,0,0,0,121,116,1,0,0,0,121,
		117,1,0,0,0,121,118,1,0,0,0,122,17,1,0,0,0,123,124,5,5,0,0,124,125,5,31,
		0,0,125,126,3,34,17,0,126,127,5,32,0,0,127,131,5,36,0,0,128,130,3,16,8,
		0,129,128,1,0,0,0,130,133,1,0,0,0,131,129,1,0,0,0,131,132,1,0,0,0,132,
		134,1,0,0,0,133,131,1,0,0,0,134,144,5,37,0,0,135,136,5,6,0,0,136,140,5,
		36,0,0,137,139,3,16,8,0,138,137,1,0,0,0,139,142,1,0,0,0,140,138,1,0,0,
		0,140,141,1,0,0,0,141,143,1,0,0,0,142,140,1,0,0,0,143,145,5,37,0,0,144,
		135,1,0,0,0,144,145,1,0,0,0,145,19,1,0,0,0,146,147,5,7,0,0,147,149,5,31,
		0,0,148,150,3,36,18,0,149,148,1,0,0,0,149,150,1,0,0,0,150,151,1,0,0,0,
		151,153,5,33,0,0,152,154,3,34,17,0,153,152,1,0,0,0,153,154,1,0,0,0,154,
		155,1,0,0,0,155,157,5,33,0,0,156,158,3,38,19,0,157,156,1,0,0,0,157,158,
		1,0,0,0,158,159,1,0,0,0,159,160,5,32,0,0,160,164,5,36,0,0,161,163,3,16,
		8,0,162,161,1,0,0,0,163,166,1,0,0,0,164,162,1,0,0,0,164,165,1,0,0,0,165,
		167,1,0,0,0,166,164,1,0,0,0,167,168,5,37,0,0,168,21,1,0,0,0,169,170,5,
		8,0,0,170,172,5,31,0,0,171,173,3,34,17,0,172,171,1,0,0,0,172,173,1,0,0,
		0,173,174,1,0,0,0,174,175,5,32,0,0,175,179,5,36,0,0,176,178,3,16,8,0,177,
		176,1,0,0,0,178,181,1,0,0,0,179,177,1,0,0,0,179,180,1,0,0,0,180,182,1,
		0,0,0,181,179,1,0,0,0,182,183,5,37,0,0,183,23,1,0,0,0,184,186,5,9,0,0,
		185,187,3,26,13,0,186,185,1,0,0,0,186,187,1,0,0,0,187,188,1,0,0,0,188,
		189,5,33,0,0,189,25,1,0,0,0,190,193,3,42,21,0,191,193,3,30,15,0,192,190,
		1,0,0,0,192,191,1,0,0,0,193,27,1,0,0,0,194,195,7,2,0,0,195,29,1,0,0,0,
		196,197,5,12,0,0,197,31,1,0,0,0,198,202,3,42,21,0,199,200,3,48,24,0,200,
		201,3,42,21,0,201,203,1,0,0,0,202,199,1,0,0,0,202,203,1,0,0,0,203,218,
		1,0,0,0,204,205,5,31,0,0,205,206,3,34,17,0,206,207,5,32,0,0,207,218,1,
		0,0,0,208,209,5,48,0,0,209,218,3,32,16,0,210,211,5,57,0,0,211,212,3,48,
		24,0,212,213,3,30,15,0,213,218,1,0,0,0,214,218,5,49,0,0,215,218,5,50,0,
		0,216,218,5,51,0,0,217,198,1,0,0,0,217,204,1,0,0,0,217,208,1,0,0,0,217,
		210,1,0,0,0,217,214,1,0,0,0,217,215,1,0,0,0,217,216,1,0,0,0,218,33,1,0,
		0,0,219,224,3,32,16,0,220,221,5,47,0,0,221,223,3,34,17,0,222,220,1,0,0,
		0,223,226,1,0,0,0,224,222,1,0,0,0,224,225,1,0,0,0,225,35,1,0,0,0,226,224,
		1,0,0,0,227,228,3,10,5,0,228,234,5,57,0,0,229,232,5,23,0,0,230,233,3,42,
		21,0,231,233,3,30,15,0,232,230,1,0,0,0,232,231,1,0,0,0,233,235,1,0,0,0,
		234,229,1,0,0,0,234,235,1,0,0,0,235,247,1,0,0,0,236,237,5,34,0,0,237,243,
		5,57,0,0,238,241,5,23,0,0,239,242,3,42,21,0,240,242,3,30,15,0,241,239,
		1,0,0,0,241,240,1,0,0,0,242,244,1,0,0,0,243,238,1,0,0,0,243,244,1,0,0,
		0,244,246,1,0,0,0,245,236,1,0,0,0,246,249,1,0,0,0,247,245,1,0,0,0,247,
		248,1,0,0,0,248,37,1,0,0,0,249,247,1,0,0,0,250,251,5,57,0,0,251,252,5,
		23,0,0,252,273,3,40,20,0,253,254,5,57,0,0,254,273,5,24,0,0,255,256,5,57,
		0,0,256,273,5,25,0,0,257,258,5,57,0,0,258,259,5,26,0,0,259,273,3,40,20,
		0,260,261,5,57,0,0,261,262,5,27,0,0,262,273,3,40,20,0,263,264,5,57,0,0,
		264,265,5,28,0,0,265,273,3,40,20,0,266,267,5,57,0,0,267,268,5,29,0,0,268,
		273,3,40,20,0,269,270,5,57,0,0,270,271,5,30,0,0,271,273,3,40,20,0,272,
		250,1,0,0,0,272,253,1,0,0,0,272,255,1,0,0,0,272,257,1,0,0,0,272,260,1,
		0,0,0,272,263,1,0,0,0,272,266,1,0,0,0,272,269,1,0,0,0,273,39,1,0,0,0,274,
		277,3,42,21,0,275,277,3,30,15,0,276,274,1,0,0,0,276,275,1,0,0,0,277,41,
		1,0,0,0,278,279,6,21,-1,0,279,280,3,44,22,0,280,289,1,0,0,0,281,282,10,
		3,0,0,282,283,7,3,0,0,283,288,3,42,21,4,284,285,10,2,0,0,285,286,7,4,0,
		0,286,288,3,42,21,3,287,281,1,0,0,0,287,284,1,0,0,0,288,291,1,0,0,0,289,
		287,1,0,0,0,289,290,1,0,0,0,290,43,1,0,0,0,291,289,1,0,0,0,292,300,3,28,
		14,0,293,300,5,57,0,0,294,295,5,31,0,0,295,296,3,42,21,0,296,297,5,32,
		0,0,297,300,1,0,0,0,298,300,3,52,26,0,299,292,1,0,0,0,299,293,1,0,0,0,
		299,294,1,0,0,0,299,298,1,0,0,0,300,45,1,0,0,0,301,302,7,5,0,0,302,47,
		1,0,0,0,303,304,7,6,0,0,304,49,1,0,0,0,305,306,7,7,0,0,306,51,1,0,0,0,
		307,308,7,8,0,0,308,317,5,31,0,0,309,314,3,26,13,0,310,311,5,34,0,0,311,
		313,3,26,13,0,312,310,1,0,0,0,313,316,1,0,0,0,314,312,1,0,0,0,314,315,
		1,0,0,0,315,318,1,0,0,0,316,314,1,0,0,0,317,309,1,0,0,0,317,318,1,0,0,
		0,318,319,1,0,0,0,319,320,5,32,0,0,320,53,1,0,0,0,321,322,5,14,0,0,322,
		323,5,52,0,0,323,324,5,31,0,0,324,325,5,32,0,0,325,329,5,36,0,0,326,328,
		3,16,8,0,327,326,1,0,0,0,328,331,1,0,0,0,329,327,1,0,0,0,329,330,1,0,0,
		0,330,332,1,0,0,0,331,329,1,0,0,0,332,333,5,37,0,0,333,55,1,0,0,0,33,59,
		69,75,82,92,121,131,140,144,149,153,157,164,172,179,186,192,202,217,224,
		232,234,241,243,247,272,276,287,289,299,314,317,329
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
