//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/Users/PC/Desktop/ProjectsAn2/LFC/ANTLRTest/ANTLRTest/Compiler.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


namespace ANTLRTest;

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class CompilerParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		COMMENT=1, IF_TOKEN=2, ELSE_TOKEN=3, FOR_TOKEN=4, WHILE_TOKEN=5, RETURN_TOKEN=6, 
		INTTOKEN=7, DOUBLETOKEN=8, FLOATTOKEN=9, STRINGTOKEN=10, WS=11, INT_TYPE=12, 
		DOUBLE_TYPE=13, FLOAT_TYPE=14, STRING_TYPE=15, PLUS=16, MINUS=17, MUL=18, 
		DIV=19, MOD=20, ASSIGN=21, INCR=22, DECR=23, PLUS_EQ=24, MINUS_EQ=25, 
		MUL_EQ=26, DIV_EQ=27, MOD_EQ=28, LPAREN=29, RPAREN=30, SEMI=31, COMMA=32, 
		DOT=33, LBRACE=34, RBRACE=35, LBRACK=36, RBRACK=37, LT=38, LEQ=39, GT=40, 
		GEQ=41, EQ=42, NEQ=43, DQUOTE=44, ID=45, BINARY_LOGICAL_OP=46, UNARY_LOGICAL_OP=47;
	public const int
		RULE_program = 0, RULE_varType = 1, RULE_numericType = 2, RULE_stringType = 3, 
		RULE_statement = 4, RULE_ifStatement = 5, RULE_forStatement = 6, RULE_whileStatement = 7, 
		RULE_returnStatement = 8, RULE_number = 9, RULE_string = 10, RULE_singleLogicalExpr = 11, 
		RULE_logicalExpr = 12, RULE_semiCol = 13, RULE_varDeclaration = 14, RULE_varAssignment = 15, 
		RULE_varValue = 16, RULE_arithmExpr = 17, RULE_atom = 18, RULE_term = 19, 
		RULE_arithmOperation = 20, RULE_factor = 21, RULE_comparators = 22, RULE_logicalOp = 23;
	public static readonly string[] ruleNames = {
		"program", "varType", "numericType", "stringType", "statement", "ifStatement", 
		"forStatement", "whileStatement", "returnStatement", "number", "string", 
		"singleLogicalExpr", "logicalExpr", "semiCol", "varDeclaration", "varAssignment", 
		"varValue", "arithmExpr", "atom", "term", "arithmOperation", "factor", 
		"comparators", "logicalOp"
	};

	private static readonly string[] _LiteralNames = {
		null, null, "'if'", "'else'", "'for'", "'while'", "'return'", null, null, 
		null, null, null, "'int'", "'double'", "'float'", "'string'", "'+'", "'-'", 
		"'*'", "'/'", "'%'", "'='", "'++'", "'--'", "'+='", "'-='", "'*='", "'/='", 
		"'%='", "'('", "')'", "';'", "','", "'.'", "'{'", "'}'", "'['", "']'", 
		"'<'", "'<='", "'>'", "'>='", "'=='", "'!='", "'\"'", null, null, "'!'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "COMMENT", "IF_TOKEN", "ELSE_TOKEN", "FOR_TOKEN", "WHILE_TOKEN", 
		"RETURN_TOKEN", "INTTOKEN", "DOUBLETOKEN", "FLOATTOKEN", "STRINGTOKEN", 
		"WS", "INT_TYPE", "DOUBLE_TYPE", "FLOAT_TYPE", "STRING_TYPE", "PLUS", 
		"MINUS", "MUL", "DIV", "MOD", "ASSIGN", "INCR", "DECR", "PLUS_EQ", "MINUS_EQ", 
		"MUL_EQ", "DIV_EQ", "MOD_EQ", "LPAREN", "RPAREN", "SEMI", "COMMA", "DOT", 
		"LBRACE", "RBRACE", "LBRACK", "RBRACK", "LT", "LEQ", "GT", "GEQ", "EQ", 
		"NEQ", "DQUOTE", "ID", "BINARY_LOGICAL_OP", "UNARY_LOGICAL_OP"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Compiler.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static CompilerParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public CompilerParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public CompilerParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(CompilerParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 51;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 35187056505332L) != 0)) {
				{
				{
				State = 48;
				statement();
				}
				}
				State = 53;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 54;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VarTypeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT_TYPE() { return GetToken(CompilerParser.INT_TYPE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOUBLE_TYPE() { return GetToken(CompilerParser.DOUBLE_TYPE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FLOAT_TYPE() { return GetToken(CompilerParser.FLOAT_TYPE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING_TYPE() { return GetToken(CompilerParser.STRING_TYPE, 0); }
		public VarTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_varType; } }
	}

	[RuleVersion(0)]
	public VarTypeContext varType() {
		VarTypeContext _localctx = new VarTypeContext(Context, State);
		EnterRule(_localctx, 2, RULE_varType);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 56;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 61440L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumericTypeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT_TYPE() { return GetToken(CompilerParser.INT_TYPE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOUBLE_TYPE() { return GetToken(CompilerParser.DOUBLE_TYPE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FLOAT_TYPE() { return GetToken(CompilerParser.FLOAT_TYPE, 0); }
		public NumericTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_numericType; } }
	}

	[RuleVersion(0)]
	public NumericTypeContext numericType() {
		NumericTypeContext _localctx = new NumericTypeContext(Context, State);
		EnterRule(_localctx, 4, RULE_numericType);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 58;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 28672L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StringTypeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING_TYPE() { return GetToken(CompilerParser.STRING_TYPE, 0); }
		public StringTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stringType; } }
	}

	[RuleVersion(0)]
	public StringTypeContext stringType() {
		StringTypeContext _localctx = new StringTypeContext(Context, State);
		EnterRule(_localctx, 6, RULE_stringType);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 60;
			Match(STRING_TYPE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SemiColContext semiCol() {
			return GetRuleContext<SemiColContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public VarDeclarationContext varDeclaration() {
			return GetRuleContext<VarDeclarationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public VarAssignmentContext varAssignment() {
			return GetRuleContext<VarAssignmentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StringTypeContext stringType() {
			return GetRuleContext<StringTypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(CompilerParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN() { return GetToken(CompilerParser.ASSIGN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StringContext @string() {
			return GetRuleContext<StringContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext arithmExpr() {
			return GetRuleContext<ArithmExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IfStatementContext ifStatement() {
			return GetRuleContext<IfStatementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ForStatementContext forStatement() {
			return GetRuleContext<ForStatementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public WhileStatementContext whileStatement() {
			return GetRuleContext<WhileStatementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ReturnStatementContext returnStatement() {
			return GetRuleContext<ReturnStatementContext>(0);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 8, RULE_statement);
		int _la;
		try {
			State = 82;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 62;
				semiCol();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 63;
				varDeclaration();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 64;
				varAssignment();
				State = 65;
				semiCol();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 67;
				stringType();
				State = 68;
				Match(ID);
				State = 71;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==ASSIGN) {
					{
					State = 69;
					Match(ASSIGN);
					State = 70;
					@string();
					}
				}

				State = 73;
				semiCol();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 75;
				arithmExpr(0);
				State = 76;
				semiCol();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 78;
				ifStatement();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 79;
				forStatement();
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 80;
				whileStatement();
				}
				break;
			case 9:
				EnterOuterAlt(_localctx, 9);
				{
				State = 81;
				returnStatement();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IfStatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IF_TOKEN() { return GetToken(CompilerParser.IF_TOKEN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(CompilerParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public LogicalExprContext logicalExpr() {
			return GetRuleContext<LogicalExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(CompilerParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] LBRACE() { return GetTokens(CompilerParser.LBRACE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE(int i) {
			return GetToken(CompilerParser.LBRACE, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] RBRACE() { return GetTokens(CompilerParser.RBRACE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE(int i) {
			return GetToken(CompilerParser.RBRACE, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ELSE_TOKEN() { return GetToken(CompilerParser.ELSE_TOKEN, 0); }
		public IfStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ifStatement; } }
	}

	[RuleVersion(0)]
	public IfStatementContext ifStatement() {
		IfStatementContext _localctx = new IfStatementContext(Context, State);
		EnterRule(_localctx, 10, RULE_ifStatement);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 84;
			Match(IF_TOKEN);
			State = 85;
			Match(LPAREN);
			State = 86;
			logicalExpr();
			State = 87;
			Match(RPAREN);
			State = 88;
			Match(LBRACE);
			State = 92;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 35187056505332L) != 0)) {
				{
				{
				State = 89;
				statement();
				}
				}
				State = 94;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 95;
			Match(RBRACE);
			State = 105;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ELSE_TOKEN) {
				{
				State = 96;
				Match(ELSE_TOKEN);
				State = 97;
				Match(LBRACE);
				State = 101;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 35187056505332L) != 0)) {
					{
					{
					State = 98;
					statement();
					}
					}
					State = 103;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 104;
				Match(RBRACE);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ForStatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FOR_TOKEN() { return GetToken(CompilerParser.FOR_TOKEN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(CompilerParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public SemiColContext semiCol() {
			return GetRuleContext<SemiColContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(CompilerParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(CompilerParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(CompilerParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public VarDeclarationContext varDeclaration() {
			return GetRuleContext<VarDeclarationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public LogicalExprContext logicalExpr() {
			return GetRuleContext<LogicalExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public VarAssignmentContext varAssignment() {
			return GetRuleContext<VarAssignmentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public ForStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_forStatement; } }
	}

	[RuleVersion(0)]
	public ForStatementContext forStatement() {
		ForStatementContext _localctx = new ForStatementContext(Context, State);
		EnterRule(_localctx, 12, RULE_forStatement);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 107;
			Match(FOR_TOKEN);
			State = 108;
			Match(LPAREN);
			State = 110;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 28672L) != 0)) {
				{
				State = 109;
				varDeclaration();
				}
			}

			State = 113;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 175922397315456L) != 0)) {
				{
				State = 112;
				logicalExpr();
				}
			}

			State = 115;
			semiCol();
			State = 117;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ID) {
				{
				State = 116;
				varAssignment();
				}
			}

			State = 119;
			Match(RPAREN);
			State = 120;
			Match(LBRACE);
			State = 124;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 35187056505332L) != 0)) {
				{
				{
				State = 121;
				statement();
				}
				}
				State = 126;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 127;
			Match(RBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class WhileStatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WHILE_TOKEN() { return GetToken(CompilerParser.WHILE_TOKEN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(CompilerParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(CompilerParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(CompilerParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(CompilerParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public LogicalExprContext logicalExpr() {
			return GetRuleContext<LogicalExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public WhileStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_whileStatement; } }
	}

	[RuleVersion(0)]
	public WhileStatementContext whileStatement() {
		WhileStatementContext _localctx = new WhileStatementContext(Context, State);
		EnterRule(_localctx, 14, RULE_whileStatement);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 129;
			Match(WHILE_TOKEN);
			State = 130;
			Match(LPAREN);
			State = 132;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 175922397315456L) != 0)) {
				{
				State = 131;
				logicalExpr();
				}
			}

			State = 134;
			Match(RPAREN);
			State = 135;
			Match(LBRACE);
			State = 139;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 35187056505332L) != 0)) {
				{
				{
				State = 136;
				statement();
				}
				}
				State = 141;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 142;
			Match(RBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ReturnStatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RETURN_TOKEN() { return GetToken(CompilerParser.RETURN_TOKEN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public SemiColContext semiCol() {
			return GetRuleContext<SemiColContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext arithmExpr() {
			return GetRuleContext<ArithmExprContext>(0);
		}
		public ReturnStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_returnStatement; } }
	}

	[RuleVersion(0)]
	public ReturnStatementContext returnStatement() {
		ReturnStatementContext _localctx = new ReturnStatementContext(Context, State);
		EnterRule(_localctx, 16, RULE_returnStatement);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 144;
			Match(RETURN_TOKEN);
			State = 146;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 35184908960128L) != 0)) {
				{
				State = 145;
				arithmExpr(0);
				}
			}

			State = 148;
			semiCol();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumberContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOUBLETOKEN() { return GetToken(CompilerParser.DOUBLETOKEN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INTTOKEN() { return GetToken(CompilerParser.INTTOKEN, 0); }
		public NumberContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_number; } }
	}

	[RuleVersion(0)]
	public NumberContext number() {
		NumberContext _localctx = new NumberContext(Context, State);
		EnterRule(_localctx, 18, RULE_number);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 150;
			_la = TokenStream.LA(1);
			if ( !(_la==INTTOKEN || _la==DOUBLETOKEN) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StringContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRINGTOKEN() { return GetToken(CompilerParser.STRINGTOKEN, 0); }
		public StringContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_string; } }
	}

	[RuleVersion(0)]
	public StringContext @string() {
		StringContext _localctx = new StringContext(Context, State);
		EnterRule(_localctx, 20, RULE_string);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 152;
			Match(STRINGTOKEN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SingleLogicalExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext[] arithmExpr() {
			return GetRuleContexts<ArithmExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext arithmExpr(int i) {
			return GetRuleContext<ArithmExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ComparatorsContext comparators() {
			return GetRuleContext<ComparatorsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(CompilerParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public LogicalExprContext logicalExpr() {
			return GetRuleContext<LogicalExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(CompilerParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode UNARY_LOGICAL_OP() { return GetToken(CompilerParser.UNARY_LOGICAL_OP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public SingleLogicalExprContext singleLogicalExpr() {
			return GetRuleContext<SingleLogicalExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(CompilerParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StringContext @string() {
			return GetRuleContext<StringContext>(0);
		}
		public SingleLogicalExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_singleLogicalExpr; } }
	}

	[RuleVersion(0)]
	public SingleLogicalExprContext singleLogicalExpr() {
		SingleLogicalExprContext _localctx = new SingleLogicalExprContext(Context, State);
		EnterRule(_localctx, 22, RULE_singleLogicalExpr);
		int _la;
		try {
			State = 170;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,14,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 154;
				arithmExpr(0);
				State = 158;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 17317308137472L) != 0)) {
					{
					State = 155;
					comparators();
					State = 156;
					arithmExpr(0);
					}
				}

				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 160;
				Match(LPAREN);
				State = 161;
				logicalExpr();
				State = 162;
				Match(RPAREN);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 164;
				Match(UNARY_LOGICAL_OP);
				State = 165;
				singleLogicalExpr();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 166;
				Match(ID);
				State = 167;
				comparators();
				State = 168;
				@string();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LogicalExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SingleLogicalExprContext singleLogicalExpr() {
			return GetRuleContext<SingleLogicalExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public LogicalOpContext[] logicalOp() {
			return GetRuleContexts<LogicalOpContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public LogicalOpContext logicalOp(int i) {
			return GetRuleContext<LogicalOpContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public LogicalExprContext[] logicalExpr() {
			return GetRuleContexts<LogicalExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public LogicalExprContext logicalExpr(int i) {
			return GetRuleContext<LogicalExprContext>(i);
		}
		public LogicalExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_logicalExpr; } }
	}

	[RuleVersion(0)]
	public LogicalExprContext logicalExpr() {
		LogicalExprContext _localctx = new LogicalExprContext(Context, State);
		EnterRule(_localctx, 24, RULE_logicalExpr);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 172;
			singleLogicalExpr();
			State = 178;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,15,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 173;
					logicalOp();
					State = 174;
					logicalExpr();
					}
					} 
				}
				State = 180;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,15,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SemiColContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMI() { return GetToken(CompilerParser.SEMI, 0); }
		public SemiColContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_semiCol; } }
	}

	[RuleVersion(0)]
	public SemiColContext semiCol() {
		SemiColContext _localctx = new SemiColContext(Context, State);
		EnterRule(_localctx, 26, RULE_semiCol);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 181;
			Match(SEMI);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VarDeclarationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumericTypeContext numericType() {
			return GetRuleContext<NumericTypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SemiColContext semiCol() {
			return GetRuleContext<SemiColContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ID() { return GetTokens(CompilerParser.ID); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID(int i) {
			return GetToken(CompilerParser.ID, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ASSIGN() { return GetTokens(CompilerParser.ASSIGN); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN(int i) {
			return GetToken(CompilerParser.ASSIGN, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext[] arithmExpr() {
			return GetRuleContexts<ArithmExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext arithmExpr(int i) {
			return GetRuleContext<ArithmExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(CompilerParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(CompilerParser.COMMA, i);
		}
		public VarDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_varDeclaration; } }
	}

	[RuleVersion(0)]
	public VarDeclarationContext varDeclaration() {
		VarDeclarationContext _localctx = new VarDeclarationContext(Context, State);
		EnterRule(_localctx, 28, RULE_varDeclaration);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 183;
			numericType();
			{
			State = 184;
			Match(ID);
			State = 187;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ASSIGN) {
				{
				State = 185;
				Match(ASSIGN);
				State = 186;
				arithmExpr(0);
				}
			}

			State = 197;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 189;
				Match(COMMA);
				State = 190;
				Match(ID);
				State = 193;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==ASSIGN) {
					{
					State = 191;
					Match(ASSIGN);
					State = 192;
					arithmExpr(0);
					}
				}

				}
				}
				State = 199;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
			State = 200;
			semiCol();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VarAssignmentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(CompilerParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN() { return GetToken(CompilerParser.ASSIGN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public VarValueContext varValue() {
			return GetRuleContext<VarValueContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INCR() { return GetToken(CompilerParser.INCR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DECR() { return GetToken(CompilerParser.DECR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUS_EQ() { return GetToken(CompilerParser.PLUS_EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS_EQ() { return GetToken(CompilerParser.MINUS_EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MUL_EQ() { return GetToken(CompilerParser.MUL_EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIV_EQ() { return GetToken(CompilerParser.DIV_EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MOD_EQ() { return GetToken(CompilerParser.MOD_EQ, 0); }
		public VarAssignmentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_varAssignment; } }
	}

	[RuleVersion(0)]
	public VarAssignmentContext varAssignment() {
		VarAssignmentContext _localctx = new VarAssignmentContext(Context, State);
		EnterRule(_localctx, 30, RULE_varAssignment);
		try {
			State = 224;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,19,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 202;
				Match(ID);
				State = 203;
				Match(ASSIGN);
				State = 204;
				varValue();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 205;
				Match(ID);
				State = 206;
				Match(INCR);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 207;
				Match(ID);
				State = 208;
				Match(DECR);
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 209;
				Match(ID);
				State = 210;
				Match(PLUS_EQ);
				State = 211;
				varValue();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 212;
				Match(ID);
				State = 213;
				Match(MINUS_EQ);
				State = 214;
				varValue();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 215;
				Match(ID);
				State = 216;
				Match(MUL_EQ);
				State = 217;
				varValue();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 218;
				Match(ID);
				State = 219;
				Match(DIV_EQ);
				State = 220;
				varValue();
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 221;
				Match(ID);
				State = 222;
				Match(MOD_EQ);
				State = 223;
				varValue();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VarValueContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext arithmExpr() {
			return GetRuleContext<ArithmExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StringContext @string() {
			return GetRuleContext<StringContext>(0);
		}
		public VarValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_varValue; } }
	}

	[RuleVersion(0)]
	public VarValueContext varValue() {
		VarValueContext _localctx = new VarValueContext(Context, State);
		EnterRule(_localctx, 32, RULE_varValue);
		try {
			State = 228;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case INTTOKEN:
			case DOUBLETOKEN:
			case LPAREN:
			case ID:
				EnterOuterAlt(_localctx, 1);
				{
				State = 226;
				arithmExpr(0);
				}
				break;
			case STRINGTOKEN:
				EnterOuterAlt(_localctx, 2);
				{
				State = 227;
				@string();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArithmExprContext : ParserRuleContext {
		public ArithmExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arithmExpr; } }
	 
		public ArithmExprContext() { }
		public virtual void CopyFrom(ArithmExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class MulDivExprContext : ArithmExprContext {
		public IToken op;
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext[] arithmExpr() {
			return GetRuleContexts<ArithmExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext arithmExpr(int i) {
			return GetRuleContext<ArithmExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MUL() { return GetToken(CompilerParser.MUL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIV() { return GetToken(CompilerParser.DIV, 0); }
		public MulDivExprContext(ArithmExprContext context) { CopyFrom(context); }
	}
	public partial class AtomExprContext : ArithmExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public AtomContext atom() {
			return GetRuleContext<AtomContext>(0);
		}
		public AtomExprContext(ArithmExprContext context) { CopyFrom(context); }
	}
	public partial class AddSubExprContext : ArithmExprContext {
		public IToken op;
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext[] arithmExpr() {
			return GetRuleContexts<ArithmExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext arithmExpr(int i) {
			return GetRuleContext<ArithmExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUS() { return GetToken(CompilerParser.PLUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS() { return GetToken(CompilerParser.MINUS, 0); }
		public AddSubExprContext(ArithmExprContext context) { CopyFrom(context); }
	}

	[RuleVersion(0)]
	public ArithmExprContext arithmExpr() {
		return arithmExpr(0);
	}

	private ArithmExprContext arithmExpr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ArithmExprContext _localctx = new ArithmExprContext(Context, _parentState);
		ArithmExprContext _prevctx = _localctx;
		int _startState = 34;
		EnterRecursionRule(_localctx, 34, RULE_arithmExpr, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			_localctx = new AtomExprContext(_localctx);
			Context = _localctx;
			_prevctx = _localctx;

			State = 231;
			atom();
			}
			Context.Stop = TokenStream.LT(-1);
			State = 241;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,22,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 239;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,21,Context) ) {
					case 1:
						{
						_localctx = new MulDivExprContext(new ArithmExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_arithmExpr);
						State = 233;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 234;
						((MulDivExprContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==MUL || _la==DIV) ) {
							((MulDivExprContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 235;
						arithmExpr(4);
						}
						break;
					case 2:
						{
						_localctx = new AddSubExprContext(new ArithmExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_arithmExpr);
						State = 236;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 237;
						((AddSubExprContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==PLUS || _la==MINUS) ) {
							((AddSubExprContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 238;
						arithmExpr(3);
						}
						break;
					}
					} 
				}
				State = 243;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,22,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class AtomContext : ParserRuleContext {
		public AtomContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_atom; } }
	 
		public AtomContext() { }
		public virtual void CopyFrom(AtomContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class NumberAtomContext : AtomContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberContext number() {
			return GetRuleContext<NumberContext>(0);
		}
		public NumberAtomContext(AtomContext context) { CopyFrom(context); }
	}
	public partial class ParenExprContext : AtomContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(CompilerParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext arithmExpr() {
			return GetRuleContext<ArithmExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(CompilerParser.RPAREN, 0); }
		public ParenExprContext(AtomContext context) { CopyFrom(context); }
	}
	public partial class IdAtomContext : AtomContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(CompilerParser.ID, 0); }
		public IdAtomContext(AtomContext context) { CopyFrom(context); }
	}

	[RuleVersion(0)]
	public AtomContext atom() {
		AtomContext _localctx = new AtomContext(Context, State);
		EnterRule(_localctx, 36, RULE_atom);
		try {
			State = 250;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case INTTOKEN:
			case DOUBLETOKEN:
				_localctx = new NumberAtomContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 244;
				number();
				}
				break;
			case ID:
				_localctx = new IdAtomContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 245;
				Match(ID);
				}
				break;
			case LPAREN:
				_localctx = new ParenExprContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 246;
				Match(LPAREN);
				State = 247;
				arithmExpr(0);
				State = 248;
				Match(RPAREN);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TermContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FactorContext[] factor() {
			return GetRuleContexts<FactorContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FactorContext factor(int i) {
			return GetRuleContext<FactorContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArithmOperationContext[] arithmOperation() {
			return GetRuleContexts<ArithmOperationContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArithmOperationContext arithmOperation(int i) {
			return GetRuleContext<ArithmOperationContext>(i);
		}
		public TermContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_term; } }
	}

	[RuleVersion(0)]
	public TermContext term() {
		TermContext _localctx = new TermContext(Context, State);
		EnterRule(_localctx, 38, RULE_term);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 252;
			factor();
			State = 258;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 2031616L) != 0)) {
				{
				{
				State = 253;
				arithmOperation();
				State = 254;
				factor();
				}
				}
				State = 260;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArithmOperationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUS() { return GetToken(CompilerParser.PLUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS() { return GetToken(CompilerParser.MINUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MUL() { return GetToken(CompilerParser.MUL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIV() { return GetToken(CompilerParser.DIV, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MOD() { return GetToken(CompilerParser.MOD, 0); }
		public ArithmOperationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arithmOperation; } }
	}

	[RuleVersion(0)]
	public ArithmOperationContext arithmOperation() {
		ArithmOperationContext _localctx = new ArithmOperationContext(Context, State);
		EnterRule(_localctx, 40, RULE_arithmOperation);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 261;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 2031616L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FactorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INTTOKEN() { return GetToken(CompilerParser.INTTOKEN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOUBLETOKEN() { return GetToken(CompilerParser.DOUBLETOKEN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FLOATTOKEN() { return GetToken(CompilerParser.FLOATTOKEN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(CompilerParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(CompilerParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ArithmExprContext arithmExpr() {
			return GetRuleContext<ArithmExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(CompilerParser.RPAREN, 0); }
		public FactorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_factor; } }
	}

	[RuleVersion(0)]
	public FactorContext factor() {
		FactorContext _localctx = new FactorContext(Context, State);
		EnterRule(_localctx, 42, RULE_factor);
		try {
			State = 271;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case INTTOKEN:
				EnterOuterAlt(_localctx, 1);
				{
				State = 263;
				Match(INTTOKEN);
				}
				break;
			case DOUBLETOKEN:
				EnterOuterAlt(_localctx, 2);
				{
				State = 264;
				Match(DOUBLETOKEN);
				}
				break;
			case FLOATTOKEN:
				EnterOuterAlt(_localctx, 3);
				{
				State = 265;
				Match(FLOATTOKEN);
				}
				break;
			case ID:
				EnterOuterAlt(_localctx, 4);
				{
				State = 266;
				Match(ID);
				}
				break;
			case LPAREN:
				EnterOuterAlt(_localctx, 5);
				{
				State = 267;
				Match(LPAREN);
				State = 268;
				arithmExpr(0);
				State = 269;
				Match(RPAREN);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ComparatorsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LT() { return GetToken(CompilerParser.LT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LEQ() { return GetToken(CompilerParser.LEQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GT() { return GetToken(CompilerParser.GT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GEQ() { return GetToken(CompilerParser.GEQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQ() { return GetToken(CompilerParser.EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEQ() { return GetToken(CompilerParser.NEQ, 0); }
		public ComparatorsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_comparators; } }
	}

	[RuleVersion(0)]
	public ComparatorsContext comparators() {
		ComparatorsContext _localctx = new ComparatorsContext(Context, State);
		EnterRule(_localctx, 44, RULE_comparators);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 273;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 17317308137472L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LogicalOpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BINARY_LOGICAL_OP() { return GetToken(CompilerParser.BINARY_LOGICAL_OP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode UNARY_LOGICAL_OP() { return GetToken(CompilerParser.UNARY_LOGICAL_OP, 0); }
		public LogicalOpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_logicalOp; } }
	}

	[RuleVersion(0)]
	public LogicalOpContext logicalOp() {
		LogicalOpContext _localctx = new LogicalOpContext(Context, State);
		EnterRule(_localctx, 46, RULE_logicalOp);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 275;
			_la = TokenStream.LA(1);
			if ( !(_la==BINARY_LOGICAL_OP || _la==UNARY_LOGICAL_OP) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 17: return arithmExpr_sempred((ArithmExprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool arithmExpr_sempred(ArithmExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 3);
		case 1: return Precpred(Context, 2);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,47,278,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,2,23,7,23,1,0,5,0,50,8,0,10,0,12,0,53,9,0,1,0,1,0,1,1,1,1,1,
		2,1,2,1,3,1,3,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,3,4,72,8,4,1,4,1,4,1,
		4,1,4,1,4,1,4,1,4,1,4,1,4,3,4,83,8,4,1,5,1,5,1,5,1,5,1,5,1,5,5,5,91,8,
		5,10,5,12,5,94,9,5,1,5,1,5,1,5,1,5,5,5,100,8,5,10,5,12,5,103,9,5,1,5,3,
		5,106,8,5,1,6,1,6,1,6,3,6,111,8,6,1,6,3,6,114,8,6,1,6,1,6,3,6,118,8,6,
		1,6,1,6,1,6,5,6,123,8,6,10,6,12,6,126,9,6,1,6,1,6,1,7,1,7,1,7,3,7,133,
		8,7,1,7,1,7,1,7,5,7,138,8,7,10,7,12,7,141,9,7,1,7,1,7,1,8,1,8,3,8,147,
		8,8,1,8,1,8,1,9,1,9,1,10,1,10,1,11,1,11,1,11,1,11,3,11,159,8,11,1,11,1,
		11,1,11,1,11,1,11,1,11,1,11,1,11,1,11,1,11,3,11,171,8,11,1,12,1,12,1,12,
		1,12,5,12,177,8,12,10,12,12,12,180,9,12,1,13,1,13,1,14,1,14,1,14,1,14,
		3,14,188,8,14,1,14,1,14,1,14,1,14,3,14,194,8,14,5,14,196,8,14,10,14,12,
		14,199,9,14,1,14,1,14,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,
		1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,3,15,225,8,
		15,1,16,1,16,3,16,229,8,16,1,17,1,17,1,17,1,17,1,17,1,17,1,17,1,17,1,17,
		5,17,240,8,17,10,17,12,17,243,9,17,1,18,1,18,1,18,1,18,1,18,1,18,3,18,
		251,8,18,1,19,1,19,1,19,1,19,5,19,257,8,19,10,19,12,19,260,9,19,1,20,1,
		20,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,3,21,272,8,21,1,22,1,22,1,23,
		1,23,1,23,0,1,34,24,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,
		38,40,42,44,46,0,8,1,0,12,15,1,0,12,14,1,0,7,8,1,0,18,19,1,0,16,17,1,0,
		16,20,1,0,38,43,1,0,46,47,298,0,51,1,0,0,0,2,56,1,0,0,0,4,58,1,0,0,0,6,
		60,1,0,0,0,8,82,1,0,0,0,10,84,1,0,0,0,12,107,1,0,0,0,14,129,1,0,0,0,16,
		144,1,0,0,0,18,150,1,0,0,0,20,152,1,0,0,0,22,170,1,0,0,0,24,172,1,0,0,
		0,26,181,1,0,0,0,28,183,1,0,0,0,30,224,1,0,0,0,32,228,1,0,0,0,34,230,1,
		0,0,0,36,250,1,0,0,0,38,252,1,0,0,0,40,261,1,0,0,0,42,271,1,0,0,0,44,273,
		1,0,0,0,46,275,1,0,0,0,48,50,3,8,4,0,49,48,1,0,0,0,50,53,1,0,0,0,51,49,
		1,0,0,0,51,52,1,0,0,0,52,54,1,0,0,0,53,51,1,0,0,0,54,55,5,0,0,1,55,1,1,
		0,0,0,56,57,7,0,0,0,57,3,1,0,0,0,58,59,7,1,0,0,59,5,1,0,0,0,60,61,5,15,
		0,0,61,7,1,0,0,0,62,83,3,26,13,0,63,83,3,28,14,0,64,65,3,30,15,0,65,66,
		3,26,13,0,66,83,1,0,0,0,67,68,3,6,3,0,68,71,5,45,0,0,69,70,5,21,0,0,70,
		72,3,20,10,0,71,69,1,0,0,0,71,72,1,0,0,0,72,73,1,0,0,0,73,74,3,26,13,0,
		74,83,1,0,0,0,75,76,3,34,17,0,76,77,3,26,13,0,77,83,1,0,0,0,78,83,3,10,
		5,0,79,83,3,12,6,0,80,83,3,14,7,0,81,83,3,16,8,0,82,62,1,0,0,0,82,63,1,
		0,0,0,82,64,1,0,0,0,82,67,1,0,0,0,82,75,1,0,0,0,82,78,1,0,0,0,82,79,1,
		0,0,0,82,80,1,0,0,0,82,81,1,0,0,0,83,9,1,0,0,0,84,85,5,2,0,0,85,86,5,29,
		0,0,86,87,3,24,12,0,87,88,5,30,0,0,88,92,5,34,0,0,89,91,3,8,4,0,90,89,
		1,0,0,0,91,94,1,0,0,0,92,90,1,0,0,0,92,93,1,0,0,0,93,95,1,0,0,0,94,92,
		1,0,0,0,95,105,5,35,0,0,96,97,5,3,0,0,97,101,5,34,0,0,98,100,3,8,4,0,99,
		98,1,0,0,0,100,103,1,0,0,0,101,99,1,0,0,0,101,102,1,0,0,0,102,104,1,0,
		0,0,103,101,1,0,0,0,104,106,5,35,0,0,105,96,1,0,0,0,105,106,1,0,0,0,106,
		11,1,0,0,0,107,108,5,4,0,0,108,110,5,29,0,0,109,111,3,28,14,0,110,109,
		1,0,0,0,110,111,1,0,0,0,111,113,1,0,0,0,112,114,3,24,12,0,113,112,1,0,
		0,0,113,114,1,0,0,0,114,115,1,0,0,0,115,117,3,26,13,0,116,118,3,30,15,
		0,117,116,1,0,0,0,117,118,1,0,0,0,118,119,1,0,0,0,119,120,5,30,0,0,120,
		124,5,34,0,0,121,123,3,8,4,0,122,121,1,0,0,0,123,126,1,0,0,0,124,122,1,
		0,0,0,124,125,1,0,0,0,125,127,1,0,0,0,126,124,1,0,0,0,127,128,5,35,0,0,
		128,13,1,0,0,0,129,130,5,5,0,0,130,132,5,29,0,0,131,133,3,24,12,0,132,
		131,1,0,0,0,132,133,1,0,0,0,133,134,1,0,0,0,134,135,5,30,0,0,135,139,5,
		34,0,0,136,138,3,8,4,0,137,136,1,0,0,0,138,141,1,0,0,0,139,137,1,0,0,0,
		139,140,1,0,0,0,140,142,1,0,0,0,141,139,1,0,0,0,142,143,5,35,0,0,143,15,
		1,0,0,0,144,146,5,6,0,0,145,147,3,34,17,0,146,145,1,0,0,0,146,147,1,0,
		0,0,147,148,1,0,0,0,148,149,3,26,13,0,149,17,1,0,0,0,150,151,7,2,0,0,151,
		19,1,0,0,0,152,153,5,10,0,0,153,21,1,0,0,0,154,158,3,34,17,0,155,156,3,
		44,22,0,156,157,3,34,17,0,157,159,1,0,0,0,158,155,1,0,0,0,158,159,1,0,
		0,0,159,171,1,0,0,0,160,161,5,29,0,0,161,162,3,24,12,0,162,163,5,30,0,
		0,163,171,1,0,0,0,164,165,5,47,0,0,165,171,3,22,11,0,166,167,5,45,0,0,
		167,168,3,44,22,0,168,169,3,20,10,0,169,171,1,0,0,0,170,154,1,0,0,0,170,
		160,1,0,0,0,170,164,1,0,0,0,170,166,1,0,0,0,171,23,1,0,0,0,172,178,3,22,
		11,0,173,174,3,46,23,0,174,175,3,24,12,0,175,177,1,0,0,0,176,173,1,0,0,
		0,177,180,1,0,0,0,178,176,1,0,0,0,178,179,1,0,0,0,179,25,1,0,0,0,180,178,
		1,0,0,0,181,182,5,31,0,0,182,27,1,0,0,0,183,184,3,4,2,0,184,187,5,45,0,
		0,185,186,5,21,0,0,186,188,3,34,17,0,187,185,1,0,0,0,187,188,1,0,0,0,188,
		197,1,0,0,0,189,190,5,32,0,0,190,193,5,45,0,0,191,192,5,21,0,0,192,194,
		3,34,17,0,193,191,1,0,0,0,193,194,1,0,0,0,194,196,1,0,0,0,195,189,1,0,
		0,0,196,199,1,0,0,0,197,195,1,0,0,0,197,198,1,0,0,0,198,200,1,0,0,0,199,
		197,1,0,0,0,200,201,3,26,13,0,201,29,1,0,0,0,202,203,5,45,0,0,203,204,
		5,21,0,0,204,225,3,32,16,0,205,206,5,45,0,0,206,225,5,22,0,0,207,208,5,
		45,0,0,208,225,5,23,0,0,209,210,5,45,0,0,210,211,5,24,0,0,211,225,3,32,
		16,0,212,213,5,45,0,0,213,214,5,25,0,0,214,225,3,32,16,0,215,216,5,45,
		0,0,216,217,5,26,0,0,217,225,3,32,16,0,218,219,5,45,0,0,219,220,5,27,0,
		0,220,225,3,32,16,0,221,222,5,45,0,0,222,223,5,28,0,0,223,225,3,32,16,
		0,224,202,1,0,0,0,224,205,1,0,0,0,224,207,1,0,0,0,224,209,1,0,0,0,224,
		212,1,0,0,0,224,215,1,0,0,0,224,218,1,0,0,0,224,221,1,0,0,0,225,31,1,0,
		0,0,226,229,3,34,17,0,227,229,3,20,10,0,228,226,1,0,0,0,228,227,1,0,0,
		0,229,33,1,0,0,0,230,231,6,17,-1,0,231,232,3,36,18,0,232,241,1,0,0,0,233,
		234,10,3,0,0,234,235,7,3,0,0,235,240,3,34,17,4,236,237,10,2,0,0,237,238,
		7,4,0,0,238,240,3,34,17,3,239,233,1,0,0,0,239,236,1,0,0,0,240,243,1,0,
		0,0,241,239,1,0,0,0,241,242,1,0,0,0,242,35,1,0,0,0,243,241,1,0,0,0,244,
		251,3,18,9,0,245,251,5,45,0,0,246,247,5,29,0,0,247,248,3,34,17,0,248,249,
		5,30,0,0,249,251,1,0,0,0,250,244,1,0,0,0,250,245,1,0,0,0,250,246,1,0,0,
		0,251,37,1,0,0,0,252,258,3,42,21,0,253,254,3,40,20,0,254,255,3,42,21,0,
		255,257,1,0,0,0,256,253,1,0,0,0,257,260,1,0,0,0,258,256,1,0,0,0,258,259,
		1,0,0,0,259,39,1,0,0,0,260,258,1,0,0,0,261,262,7,5,0,0,262,41,1,0,0,0,
		263,272,5,7,0,0,264,272,5,8,0,0,265,272,5,9,0,0,266,272,5,45,0,0,267,268,
		5,29,0,0,268,269,3,34,17,0,269,270,5,30,0,0,270,272,1,0,0,0,271,263,1,
		0,0,0,271,264,1,0,0,0,271,265,1,0,0,0,271,266,1,0,0,0,271,267,1,0,0,0,
		272,43,1,0,0,0,273,274,7,6,0,0,274,45,1,0,0,0,275,276,7,7,0,0,276,47,1,
		0,0,0,26,51,71,82,92,101,105,110,113,117,124,132,139,146,158,170,178,187,
		193,197,224,228,239,241,250,258,271
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
